### ISSUE TITLE
module.exports inside the browser?

### ISSUE THREAD

**Issue by lfv89** [Wizcorp/phonegap-facebook-plugin#1030]
When I'm runing the facebookConnectPlugin in my desktop browser (outside a cordova app on the device), I get this error: `Uncaught ReferenceError: module is not defined`.

From my understanding, when the `cordova.platformId == 'browser'` the facebookConnectPlugin.js file should'nt call `module.exports`, since it only makes sense inside a node process, and not inside a browser.

What do you think?

**Comment by lordlothar99** [comment]
+1

**Comment by tiagosampaio** [comment]
+1

**Comment by nhoctanker** [comment]
+1

**Comment by ghost** [comment]
any feedback on this plzzz?

**Comment by josewilker** [comment]
nobody answer nothing? wtf?

**Comment by ShoboySnr** [comment]
Having the same issues with this.. Any fix?
