### ISSUE TITLE
TypeError: Cannot read property 'browserInit' of undefined

### ISSUE THREAD

**Issue by ShubhamBadal** [Wizcorp/phonegap-facebook-plugin#1048]
I want to run on browser for testing and ui development, don't want to do that on phone or emulator everytime. I saw http://ngcordova.com/docs/plugins/facebook/ and under web development section saw this is possible. Made changes as said in config.js but I am getting this error.

Uncaught ReferenceError: cordova is not defined
TypeError: Cannot read property 'browserInit' of undefined

I have added facebookConnectPlugin.js to index.html
I have added < div id="fb-root" > < /div > inside body of index.html

I am using Cordova/Ionic.

**Comment by kaumac** [comment]
Same problem as @ShubhamBadal. I've been trying to use this on browser for 6 months now, tried on about 3 different projects started from the ground, tried every possible proposed solution I found on Google, and still have the same problem.

It does work on Android/iOS, but it simply won't work on the browser no matter what, so I have to rebuild and run no device and this is pretty bad for debugging

**Comment by raphaelduartepinheiro** [comment]
@kaumac @ShubhamBadal  when you call browserInit, the code try to reach for:

    this.browserInit = function (id, version) {
      this.appID = id;
      this.appVersion = version || "v2.0";  
      facebookConnectPlugin.browserInit(this.appID, this.appVersion);
    };

*facebookConnectPlugin* is undefined because it's a Cordova plugin and will not work on web (unless you use Browser platform...)

To make it work, put this dependency in your bower.json:

`"facebook-connect-plugin": "https://cdn.rawgit.com/Wizcorp/phonegap-facebook-plugin/master/facebookConnectPlugin.js"`

`bower update`

And add to *index.html* *lib/facebook-connect-plugin/index.js* reference.

You can remove the Cordova conditional, and make this javascript for web.

It's done!

Btw, I'd like to suggest 2 ideas:

1) Split this file in two. One for web, other for mobile devices (maybe not a good idea, but is an option)
2) Enhance this plugin to work both as cordova/phonegap plugin and web library.

**Comment by kaumac** [comment]
Thanks for your reply @raphaelduartepinheiro, I tried doing it but it still doesn't work, after removing the conditional I'm getting a "module is not defined" error

**Comment by raphaelduartepinheiro** [comment]
@kaumac sorry, I've forgot to mention. Please, comment *module.exports*. :)
Here is a gist that exemplifies what index.js must look like:

https://gist.github.com/raphaelduartepinheiro/67f5a8663c5a7fe2cd02

**Comment by kaumac** [comment]
Thanks @raphaelduartepinheiro I'm not getting module as undefined, but when calling login() method I get "FB is not defined".

I must be doing something wrong :disappointed:

**Comment by raphaelduartepinheiro** [comment]
In my case I load the facebook SDK (sdk.js) synchronously
    <script src="http://connect.facebook.net/en_US/sdk.js" type="text/javascript"></script>

But you can check the gist (I've edited) now, I uncommented the sdk fetch.

**Comment by kaumac** [comment]
Perfect! Thanks @raphaelduartepinheiro, it works!

Completely unrelated with this issue, how did you config your Facebook to test your app locally?
I'm accessing my app on 192.168.2.23 and I get this error when I try to login:
<img width="468" alt="captura de tela 2015-07-25 as 00 16 53" src="https://cloud.githubusercontent.com/assets/1170740/8887680/02321314-3263-11e5-9b57-36ae9ded07cc.png">
It's working fine on Android though

@ShubhamBadal could you close this issue? I think that the approach suggested by @raphaelduartepinheiro will probably solve your problem.

**Comment by raphaelduartepinheiro** [comment]
@kaumac in developer.facebook.com, go to your app, settings, advanced, and put your localhost:port in the allowed urls. This is a very common issue, you can find it on Google.

**Comment by kaumac** [comment]
Thanks a lot man, I was trying an answers that I found on StackOverflow that said to place the IP on the Basic tab, placing it on the Advanced tab did the trick. Thanks a lot!

**Comment by ShubhamBadal** [comment]
I will try the discussed solutions some day when I get some time! 
But Thank you anyway! I hope it will work, so closing the issue.
