### ISSUE TITLE
Android Jar mismatch with com.onesignal.plugins.onesignal

### ISSUE THREAD

**Issue by Omnem** [Wizcorp/phonegap-facebook-plugin#1056]
The moment I've added the OneSignal plugin, the build for Android failed with the following error:

[dependency] Found 2 versions of android-support-v4.jar in the dependency list,
[dependency] but not all the versions are identical (check is based on SHA-1 only at this time).
[dependency] All versions of the libraries must be the same at this time.
[dependency] Versions found are:
[dependency] Path: /project/com.phonegap.plugins.facebookconnect/cyberdunk-FacebookLib/libs/android-support-v4.jar
[dependency] 	Length: 758727
[dependency] 	SHA-1: efec67655f6db90757faa37201efcee2a9ec3507
[dependency] Path: /project/libs/android-support-v4.jar
[dependency] 	Length: 987314
[dependency] 	SHA-1: 9b6a9a9078af571732159b904ad423b03b7cc786

BUILD FAILED
/home/ec2-user/android-sdk/tools/ant/build.xml:573: Jar mismatch! Fix your dependencies

It seems the facebookConnect plugin and oneSignal are using different android libraries.

Is there a known fix ? Any 2 versions of the two plugins are compatible ? Any thoughts ? 
It seems to build on iOS.

I've tried some of the fixes mentioned in issue #812 with no success.

Thank you

**Comment by jkasten2** [comment]
Unfortunately this facebook plugin includes `android-support-v4.jar` instead of externally defining it as a dependency like OneSignal does. As a work around to get OneSignal working you can delete `<project-root>\platforms\android\libs\android-support-v4.jar` and build again.

Thanks.

**Comment by Omnem** [comment]
The solution offered by @jkasten2 worked for me (local build). Feel free to close this.

**Comment by jkasten2** [comment]
We just added our plugin to [npmjs](https://www.npmjs.com/package/onesignal-cordova-plugin) and updated it to use gradle to handle dependencies but it did not fix this issue with this official fork.

However, there is a fork of this plugin [cordova-plugin-facebook4](https://www.npmjs.com/package/cordova-plugin-facebook4) that builds just fine with our [onesignal-cordova-plugin](https://www.npmjs.com/package/onesignal-cordova-plugin).

Let us know if it works for you.

Thanks.

**Comment by jkasten2** [comment]
We just released a PhoneGap Build compatibility version that removes the linked dependencies. This fixes all conflict issues with other plugins that use Google Play services or Android Support library v4 or v13 like the facebook plugin.

For Adobe PhoneGap Build users using com.phonegap.plugins.facebookconnect and OneSignal, include the following your config.xml file instead of "com.onesignal.plugins.onesignal":
```xml
<gap:plugin name="onesignal-cordova-plugin-pgb-compat" source="npm" />
<gap:plugin name="com.google.playservices" source="npm" />
```

For all other forks of Cordova using gradle builds (CLI, PhoneGap CLI, Intel XDK, Ionic, etc) I would use cordova-plugin-facebook4 and onesignal-cordova-plugin.

Thanks.

**Comment by Omnem** [comment]
Works both locally and on phonegap's build, thank you @jkasten2.

```
<gap:plugin name="onesignal-cordova-plugin-pgb-compat" source="npm" />
<gap:plugin name="com.google.playservices" source="npm" />

<gap:plugin name="com.phonegap.plugins.facebookconnect" version="0.9.0"> 
        <param name="APP_ID" value="..." />
        <param name="APP_NAME" value="..." />
    </gap:plugin>    
```
with  

```
<preference name='phonegap-version' value='cli-5.1.1' />
```

See this link for the entire conversation back on onesignal's repo:
https://github.com/one-signal/OneSignal-Cordova-SDK/issues/2#
