### ISSUE TITLE
Migration to NPM

### ISSUE THREAD

**Issue by keab42** [Wizcorp/phonegap-facebook-plugin#1060]
Are you intending to list this project on NPM now that plugins.cordova.io is in ReadOnly mode?

**Comment by thedarkman123** [comment]
Whats going on with this? 2 more months and no more facebook-plugin phonegap build?

**Comment by remcohaszing** [comment]
I would like to see this as well.

**Comment by jrouault** [comment]
Sorry for the (quite long) wait. You can expect it to be done by the end of next week.

**Comment by jrouault** [comment]
The plugin is now available on npm:
https://www.npmjs.com/package/phonegap-facebook-plugin
