### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by omeralper** [Wizcorp/phonegap-facebook-plugin#1109]
I am getting an error message from facebook app when I hit login

Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings. To use this URL you must add a valid native platform in your App's settings.

Error message is clear enough but the problem is I cannot add native platform at my facebook settings because my application is at development stage. I don't have an appstore id and bundle id for my app yet. Any suggestions?

**Comment by im7mortal** [comment]
I had this problem two hours ago. 
You need add android platform in settings of your app. Just follow instructions.

**Comment by MartinKip** [comment]
I have the same error message, even though I have an Android application in my Facebook app. Any other suggestions? Even weirer is that it worked, and then over the weekend it just stopped working.

**Comment by omeralper** [comment]
I get this error at ios, haven't tried on android yet.

**Comment by im7mortal** [comment]
Facebook dashboard have very **treacherous interface**. 
I have recently done work with key hashes. Interface just wasn't saving my wrong key. But via a button "quick start"  it just auto filled my key every time. And when I checked it in settings panel field was empty. When I tried put my key via settings panel it put my key in field but after refresh page it again was empty.
And only when I put right key via settings panel it gave me **popup "saved"**. I checked it couple time with  wrong and right keys. And had the same result. (check popup "saved" if you have problem with key hashes)
When I registered new "Site URL" in Website. It had not been working until I did it via a button "quick start". The same URL!! i tried a lot of time. 
It is'not issue of this plugin.
Be careful guys! Good luck!

**Comment by scottopolis** [comment]
I had this issue, I solved it by going to my app dashboard at https://developers.facebook.com/apps, select "Choose a Platform," and add iOS. Scroll down the dialog to add your app ID, then save.

I also have the domain under Basic->App Domains.  To support the browser login, I have Client OAuth Login set to True under Advanced.

**Comment by aogilvie** [comment]
@omeralper Please try the above and re-open this issue if you still have problems.

**Comment by ansarikhurshid786** [comment]
I am also facing same problem. can anybody help me
