### ISSUE TITLE
Like button for facebook pages

### ISSUE THREAD

**Issue by sdw** [Wizcorp/phonegap-facebook-plugin#1111]
Hi!

in the troubleshooting page you suggest implementing a like button using the og.likes Facebook API call.

However this doesn't work for Facebook pages.

How do I do a "like" button that works with facebook pages in my app, using the facebook plugin?

**Comment by ericman93** [comment]
+1

**Comment by ericman93** [comment]
its seems that facebook does not implement page likes via graph.

> For Facebook Pages or websites that do not integrate with Facebook Authentication, developers should continue to use the Like button social plugin.

**Comment by ericman93** [comment]
its seems that Facebook dosn't support page likes.

> For Facebook Pages or websites that do not integrate with Facebook Authentication, developers should continue to use the Like button social plugin.

**Comment by sdw** [comment]
Unfortunately the standard Facebook social plugin doesn't seem to work in phonegap

**Comment by aogilvie** [comment]
Yup not supported by FB.
