### ISSUE TITLE
On Xcode  -  Comparison of constant 2 with boolean expression is always false

### ISSUE THREAD

**Issue by ronyrun** [Wizcorp/phonegap-facebook-plugin#1127]
On Xcode  - /app/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m:238:28: Comparison of constant 2 with boolean expression is always false

![image](https://cloud.githubusercontent.com/assets/7273443/10101330/581521ca-6398-11e5-9769-4de7a34f1a12.png)

**Comment by santimaya** [comment]
Same issue here!

**Comment by aogilvie** [comment]
Hi, this has been updated on develop branch. Thanks for the report.

https://github.com/Wizcorp/phonegap-facebook-plugin/blob/develop/platforms/ios/HelloCordova/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m#L238

**Comment by ronyrun** [comment]
your welcome :)
