### ISSUE TITLE
[Discuss][Android] Replace Facebook SDK code with gradle dependency

### ISSUE THREAD

**Issue by sgrebnov** [Wizcorp/phonegap-facebook-plugin#1128]
Are there any objectives not to switch to gradle dependency below instead of keeping SDK locally? [Here](https://github.com/Wizcorp/phonegap-facebook-plugin/pull/1017#issuecomment-142811456) is a prove link that it works

```
<framework src="com.facebook.android:facebook-android-sdk:3.23.0" />
```

The only concern I see here is that we won't support ant build system anymore, but I don't think this is important taking into account we've switched to gradle as a default one in Cordova long time ago.

**Comment by jeduan** [comment]
I'm using this, and the issue I can think of is that I'm not sure wether Phonegap Build supports the framework tag. I agree this is the better path facing to the future

**Comment by sgrebnov** [comment]
As per this [announce](http://phonegap.com/blog/2015/06/16/phonegap-updated-on-build/) PGBuild uses `cordova-cli@5.1.1` which should play nice w/ gradle dependencies

**Comment by jfaris** [comment]
Unfortunately they mention at the end of that post that Phonegap Build (PGB) does not support gradle builds yet. They had to fork the crosswalk plugin to make it work with an ant build for PGB.

I really do hope that PGB gets gradle support soon. Until then there isn't a good way to have this plugin work for everybody using PGB.

**Comment by sgrebnov** [comment]
I see, makes perfect sense

**Comment by sgrebnov** [comment]
I'm going to take a look on this one more time as per this announce [Android Builds Now Using Gradle By Default](http://phonegap.com/blog/2015/09/28/android-using-gradle/)

**Comment by keab42** [comment]
Good idea. Being able to use a fixed Gradle dependency should make it play nice and resolve a lot of the current issues that users are having getting this plugin working on Android.

**Comment by sgrebnov** [comment]
I've performed a quick test and confirm that `framework`(gradle) is now fully supported. I plan to propose a PR which switches to a gradle dependency later this week. Should it goes to develop branch? - please confirm

Sample build (`cli-5.2.0`) (https://build.phonegap.com/apps/1704341/logs/android/build/)
```
Build Date: 2015-10-12 13:23:46 +0000
----------------------------------------------
Running: /project/gradlew cdvBuildDebug -b /project/build.gradle -Dorg.gradle.daemon=true
Download https://repo1.maven.org/maven2/com/facebook/android/facebook-android-sdk/3.23.0/facebook-android-sdk-3.23.0.pom
Download https://repo1.maven.org/maven2/com/parse/bolts/bolts-android/1.1.4/bolts-android-1.1.4.pom
Download https://repo1.maven.org/maven2/com/parse/bolts/bolts-android/1.1.4/bolts-android-1.1.4.jar
Download https://repo1.maven.org/maven2/com/facebook/android/facebook-android-sdk/3.23.0/facebook-android-sdk-3.23.0.aar
:preBuild

...

:cdvBuildDebug

BUILD SUCCESSFUL

Total time: 27.859 secs
Built the following apk(s):
    /project/build/outputs/apk/project-debug.apk
```
PS. I had to add the following settings to enable gradle build (I thought it should be a default one, but it seems it is not)

```
<preference name="android-build-tool" value="gradle" />
```

**Comment by sgrebnov** [comment]
Proposed patch https://github.com/Wizcorp/phonegap-facebook-plugin/pull/1148 to `develop` branch

**Comment by sgrebnov** [comment]
Closing discussion as proposed change has been applied to `develop` branch.
