### ISSUE TITLE
Not working on PGB Service

### ISSUE THREAD

**Issue by skoreno1** [Wizcorp/phonegap-facebook-plugin#1129]
Hey mate whats the correct URL for the plugin when using the npm service because it won't let me build the App with the Facebook connect plugin. i'm using this atm.

gap:plugin name="cordova-plugin-facebookconnect-orlando" source="npm" 
param name="APP_ID" value="####" 
param name="APP_NAME" value="#####" 
gap:plugin

**Comment by jrouault** [comment]
This plugin is now on npm. See #1060.
