### ISSUE TITLE
#import <FacebookSDK/FacebookSDK.h> file not found IOS9

### ISSUE THREAD

**Issue by rijeka2008** [Wizcorp/phonegap-facebook-plugin#1139]
I have issue with phonegap app, can somebody help?

#import <FacebookSDK/FacebookSDK.h> file not found IOS9

**Comment by rijeka2008** [comment]
Solved..

**Comment by mahnuh** [comment]
How did you solve this?

**Comment by rijeka2008** [comment]
I used older facebook sdk that it is supported by plugin, latest sdk is not.
