### ISSUE TITLE
Facebook does not send callback

### ISSUE THREAD

**Issue by s1lviu** [Wizcorp/phonegap-facebook-plugin#1142]
I use Ionic framework with ngCordova plugin. I have a button in my app that calls a facebook login function. All works fine on browser, but not on native Android device with Facebook app installed.

At first press on facebook login button (on device) the Facebook authorize page is displayed in app. I press OK, redirects me back to app, but nothing.

At second press on facebook login button, all works fine, all code inside $cordovaFacebook.login([...]) runs perfectly.

**Comment by lichutin** [comment]
As for me facebook doesn`t send shareDialog callbacks at all but other works well (such as graphApi and login)

**Comment by s1lviu** [comment]
I have solved. I have receiving oAuth error and the solution was calling again the facebook login function.
