### ISSUE TITLE
IOS & Android - PGB build failed

### ISSUE THREAD

**Issue by CyrilleGuimezanes** [Wizcorp/phonegap-facebook-plugin#1173]
Hello,

Since few days, I'm not able to build my PGB project with FacebookConnectPlugin added. 

**Related config.xml**
`   <preference name="phonegap-version" value="cli-5.2.0" />`
`   <preference name="android-targetSdkVersion" value="19" />`
`  <gap:plugin name="phonegap-facebook-plugin"  version="0.12.0" source="npm">`
`       <param name="APP_ID" value="XXXXX" /> `
 `      <param name="APP_NAME" value="XXXXX" />`
`  </gap:plugin>`

**Android logs**
>BUILD FAILED
>/android-sdk/tools/ant/build.xml:597: The following error occurred while executing this line:
>/project/phonegap-facebook-plugin/nego-FacebookLib/custom_rules.xml:4: /project/phonegap->facebook-plugin/nego-FacebookLib/ant-build does not exist.
>
>Total time: 9 seconds
>
>/project/cordova/node_modules/q/q.js:126
>                    throw e;
>                    ^
>Error code 1 for command: ant with args: release,-f,/project/build.xml

**IOS logs**
> The following build commands failed:
> 	CompileC build/MyProject.build/Release-iphoneos/MyProject.build/Objects-> > normal/armv7/FacebookConnectPlugin.o MyProject/Plugins/phonegap-facebook-> >plugin/FacebookConnectPlugin.m normal armv7 objective-c >com.apple.compilers.llvm.clang.1_0.compiler
>(1 failure)

I have this issue since I update to CLI5.2 (needed by an other plugin) & use 0.12.0 on npm.

Could you help me?

**Comment by bau720123** [comment]
+1

**Comment by kljuco** [comment]
+1

**Comment by celwell** [comment]
+1

**Comment by farlop** [comment]
+1

**Comment by lawsonk1215** [comment]
I was able to fix this by removing the android platform all together and re-adding it
```
cordova platform remove android
```
```
cordova platform add android
```
Then make sure you open up the AndroidManifest.xml for the phonegap-facebook-plugin and add these lines
```
<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="17" />
```

**Comment by FlossyWeb** [comment]
+1

**Comment by celwell** [comment]
@lawsonk1215 we are referring to a pg build problem

**Comment by CyrilleGuimezanes** [comment]
Good news! I found a solution!

Tou have to add (edit) you config.xml as it:

`<preference name="android-minSdkVersion" value="16" />`
`<preference name="android-build-tool" value="gradle" />`
`<gap:plugin name="phonegap-facebook-plugin"  source="npm">`
`    <param name="APP_ID" value="XXXX" />`
`   <param name="APP_NAME" value="XXXXX" />`
` </gap:plugin>`

**Bonus:**
If you want to update to a new Facebook SDK juste change **phonegap-facebook-plugin** by **cordova-plugin-facebook4** which refer to this fork https://github.com/jeduan/cordova-plugin-facebook4

**Comment by bau720123** [comment]
thanks @CyrilleGuimezanes

**Comment by auching** [comment]
@CyrilleGuimezanes it's not working on iOS :(

**Comment by CyrilleGuimezanes** [comment]
@auching It's not building? Your logs have they changed? Maybe a plugin on your list does not support Gradle...
My application built succefully on IOS :/

**Comment by bau720123** [comment]
hi @auching 
just like @CyrilleGuimezanes said
please use these syntax code in your config.xml
```
<preference name="android-build-tool" value="gradle" />
<preference name="android-minSdkVersion" value="15" />
<gap:plugin name="cordova-plugin-facebook4" source="npm" version="1.4.0">
 <param name="APP_ID" value="your_app_id" />
 <param name="APP_NAME" value="your_app_name" />
</gap:plugin>
```
that's all

**Comment by auching** [comment]
@CyrilleGuimezanes @bau720123 
but these two lines are meant for Android right?

<preference name="android-build-tool" value="gradle" />
<preference name="android-minSdkVersion" value="15" />

I have no problem building with Android, just can't build iOS :(

**Comment by bau720123** [comment]
hi @auching 
ios is build success too
are you using cli-5.2.0 ?
```
<preference name="phonegap-version" value="cli-5.2.0" />
```

**Comment by auching** [comment]
@bau720123 
yes 5.2.0, and i use "phonegap-facebook-plugin" instead of "cordova-plugin-facebook4" because the share dialogue in "cordova-plugin-facebook4" is broken

**Comment by bau720123** [comment]
well @auching 
if you use "cordova-plugin-facebook4" first，if will build success ?

**Comment by MaicolBen** [comment]
@bau720123 There is no solution for Phonegap 3.x?

**Comment by CyrilleGuimezanes** [comment]
As this is issue seem to be **resolved** for the **majority** and start to be a bit offtopic I close it.... 

For those who still have an issue I recommand to post on StackOverflow and refer to http://stackoverflow.com/questions/33526773/how-to-use-phonegap-facebook-plugin-under-cli-5-2-pgb (which I used to solved the problem).

I will make a pull request to edit the PGB documentation for **cordova-plugin-facebook4** and **phonegap-facebook-plugin** asap.

**Comment by bau720123** [comment]
hi @MaicolBen 
there is no solution for 3.X version
3.X that I think really a old version
maybe you can consider update it
