### ISSUE TITLE
Problems installing pluguin by build.phonegap

### ISSUE THREAD

**Issue by ivanssa** [Wizcorp/phonegap-facebook-plugin#1188]
Hello I'm having problems when trying to install the script by build.phonegap.com've done everything researched in various places and I find the solution I made the settings in xml and send the zip to biuld www config.xml and get an error the plugin is not supported via npm, please help me with step by poasso, for I am about to give up using the plugin for native login and opting to use popups same.

```
<plugin name="com.phonegap.plugins.facebookconnect" version="0.12.0">
		<param name="APP_ID" value="123456"/>
		<param name="APP_NAME" value="myappname"/>
    </plugin>
```

**Comment by bau720123** [comment]
hi @ivanssa 
please use this to instead
```
<gap:plugin name="cordova-plugin-facebook4" source="npm" version="1.4.0">
 <param name="APP_ID" value="aaa" />
 <param name="APP_NAME" value="bbb" />
</gap:plugin>
```

**Comment by ewsopp** [comment]
@bau720123 - cordova-plugin-facebook4 is another plugin, no?

**Comment by bau720123** [comment]
hi @ewsopp 
detail all right here
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#co-existing-with-facebook-plugin
