### ISSUE TITLE
android build errors : major android-support-v4 conflicts

### ISSUE THREAD

**Issue by boten** [Wizcorp/phonegap-facebook-plugin#1189]
my app is build with ionic 1.1.1 (cordova) 
and i am using these 3 plugins :
-- cordova-plugin-google-analytics (cordova plugin add cordova-plugin-google-analytics)
-- pushwoosh-cordova-plugin (cordova plugin add pushwoosh-cordova-plugin)
-- de.appplant.cordova.plugin.local-notification  (cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications)

unfortunately  i cant add the facebook-plugin -> my android build keeps crashing (ios all good).

UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)

** i read all the comments with ref to the android-support-v4 conflicts and tried the fixes but each fix of one plug is crashing the other ? 

if any 1 can pls help me create an app where all 4 plugins play nicely together it would help me a lot

**Comment by Clebiez** [comment]
Hi,
Please try the solution that I posted on this issue : https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1183

**Comment by boten** [comment]
its working , thanx :)
