### ISSUE TITLE
How do i get user_friends and email api data from single Request

### ISSUE THREAD

**Issue by sathiyaraj-tag** [Wizcorp/phonegap-facebook-plugin#1192]
I can write a logic for email is one request after user_friends is another request i will sent to facebook server. But i want get a single request for all data like email and user_friend api.

**Comment by jeduan** [comment]
you can check out the Graph API explorer to figure out what you want to do https://developers.facebook.com/tools/explorer/

I don't see a bug with this plugin, so I'm closing this, feel free to reopen if there's an actual bug.
