### ISSUE TITLE
Authentication with native Facebook?

### ISSUE THREAD

**Issue by ivanssa** [Wizcorp/phonegap-facebook-plugin#1219]
hello could someone tell me if it is possible to make authentication on my facebook app without having to open a popup which asks User and Password ? I would like to use the credentials of the native facebook app installed on the client account ? What code should I use ? I 'm trying this the day could only operate the method login via popup that asks login and password facebook , I am using authentication with ionic and firebase .

**Comment by ammar08429** [comment]
I do not understand your question totally,
But you can use this plugin to have a native facebook api login, you will have to register your mobile app in facebook app that you created and use this plugin in your mobile app

The user wont see a pop up, he will be redirected to fb to allow your app to take data thats it.

If you are seeing pop up that mens you have configured web in facebook app and you are using the js method in you mobile app

**Comment by ivanssa** [comment]
Thanks for the feedback, I realized that it is nothing related to the plugin, but was willing to have an experience via app in ios9 but after reading the dev blog facebook https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9/ saw that they have changed the way authenticates users via browser, I realized that several aplicaivos like instagram, pinterest etc .. also moved to the browser, unfortunately we have to accept it for now :-(

**Comment by MaicolBen** [comment]
@ivanssa Did you tried [this workaround](https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1116#issuecomment-152369032)? You have to add some entries to the plist file of your xcode project.

**Comment by ivanssa** [comment]
@MaicolBen Thank you, I'm working with phonegap I saw this solution these days but added in my config.xml but after running the build.phonegap nothing has changed still have the the authentication done via Safari browser :-( realized that many applications that have changed tb pinterest, instagram etc .. so I guess I have no choice.

```
<gap:config-file platform="ios" parent="LSApplicationQueriesSchemes" overwrite="true">
    <array>
        <string>fbapi</string>
        <string>fbapi20130214</string>
        <string>fbapi20130410</string>
        <string>fbapi20130702</string>
        <string>fbapi20131010</string>
        <string>fbapi20131219</string>
        <string>fbapi20140410</string>
        <string>fbapi20140116</string>
        <string>fbapi20150313</string>
        <string>fbapi20150629</string>
        <string>fbauth</string>
        <string>fbauth2</string>
        <string>fb-messenger-api20140430</string>
    </array>
</gap:config-file>
```

**Comment by MaicolBen** [comment]
@ivanssa Yes, I tried that for PB and it seems to not work. I've to drop PB and get it work locally.

**Comment by ivanssa** [comment]
@MaicolBen  I just wanted the user to approve the easy way to app instead of each time having to open Safari to enter your password, unfortunately facebook regressed with this and it is frustrating to see the user typing your credentials and getting a return that "you have approved this app "now approved the app because then bundled login and password again? unfortunate that facebook did ...
