### ISSUE TITLE
0.4.2 is actually 0.4.0

### ISSUE THREAD

**Issue by alaaghribi** [Wizcorp/phonegap-facebook-plugin#1260]
I'd like to install the **0.4.2** version (to have only the 64 bits support), but after installing it I have always 

```
cordova plugin list
com.phonegap.plugins.facebookconnect 0.4.0 "Facebook Connect"
```

Can you please verify that 0.4.2 is actually 0.4.2 and fix the download link ?

I really need that version, otherwise, I have to spend so much time to change API requests for the 0.12 version.

Thank you very much .

**Comment by andrewbusch7** [comment]
Alternatively you could clone this repository to your machine, and pick the exact commit you want. It's much faster that way for builds ongoing, as removes the need to check an offsite repo.

It's just that 0.4.2 is now over 2 years old (5th March 2014), and it's better that the contributors focus on issues with the latest version.

**Comment by alaaghribi** [comment]
Thank you for your response :) !.
