### ISSUE TITLE
ReferenceError: facebookConnectPlugin is not defined on iOS device

### ISSUE THREAD

**Issue by kristiyandobrev** [Wizcorp/phonegap-facebook-plugin#1275]
Hello,

I guess many of you are familiar with the following issue, while developing / testing in browsers : 

> ReferenceError: facebookConnectPlugin is not defined

I just started getting the same issue but on iOS device, like never before. 

If that would help, this is how am I using the plugin in my Ionic app.
1. Installation : 

Locally cloned the repo and installed with `cordova plugin add /PATH/TO/LOCAL/COPY --variable APP_ID="APPID" --variable APP_NAME="myApplication"`.
1. **index.html**  --> [GIST](https://gist.github.com/kristiyandobrev/e1efd84c2f33716079252c15245da9ac)
2. **controller.js** --> [GIST](https://gist.github.com/kristiyandobrev/4cf2fc32e56a9a70ac866a1797f5c8e9)

**Comment by marcusengel** [comment]
I still have this issue in the browser.
Is it failing for you in the browser?

**Comment by kristiyandobrev** [comment]
@marcusengel Yes. But i fixed it by using this plugin --> https://github.com/Telerik-Verified-Plugins/Facebook
