### ISSUE TITLE
Refused to display in a frame because it set 'X-Frame-Options' to 'DENY'.

### ISSUE THREAD

**Issue by MTeres** [Wizcorp/phonegap-facebook-plugin#1281]
**Refused to display ['URL'] in a frame because it set 'X-Frame-Options' to 'DENY'.**

When i call 

`function loginFace(){
    facebookConnectPlugin.login(['email'], function(response) {
            alert('Logged in');
            alert(JSON.stringify(response.authResponse));
        }, function(error){
            alert(error);
    })
  }`

**Comment by caioavidal** [comment]
Same issue here

**Comment by sideral** [comment]
+1

**Comment by payas** [comment]
same

**Comment by pjmazenot** [comment]
Same for me

**Comment by arielsantana** [comment]
Same

**Comment by antontsvil** [comment]
If you're using cordova-plugin-inappbrowser and running into this issue when testing in browser, check [the other issue out](https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1133) for possible solutions
