### ISSUE TITLE
Track app installs

### ISSUE THREAD

**Issue by pke** [Wizcorp/phonegap-facebook-plugin#1323]
It seems this plugin is not able to simply track app installs, is it?
I don't need my app to login to FB, I just want to submit an app install event to FB.

**Comment by rossvz** [comment]
@pke did you ever receive an answer to this question? Im looking for the same functionality

**Comment by pke** [comment]
@rossvz I am using https://github.com/jeduan/cordova-plugin-facebook4 now and it works out of the box.
