### ISSUE TITLE
Phonegap repository off - "FacebookLib does not exist error" when building to android

### ISSUE THREAD

**Issue by mateusredfield** [Wizcorp/phonegap-facebook-plugin#1332]
Phonegap open repository no longers exists. And when I do on config.xml:

```
<plugin spec="https://github.com/Wizcorp/phonegap-facebook-plugin.git" source="git" >
      <param name="APP_ID" value=<VALUE> />
      <param name="APP_NAME" value=<NAME> />
</plugin>
```

And building on build.phonegap it gives an error saying:

BUILD FAILED
/android-sdk/tools/ant/build.xml:597: The following error occurred while executing this line:
/project/phonegap-facebook-plugin/customer-FacebookLib/custom_rules.xml:4: /project/phonegap-facebook-plugin/customer-FacebookLib/ant-build does not exist.

Total time: 5 seconds

/project/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: ant with args: release,-f,/project/build.xml

**Comment by jmaicaaan** [comment]
Hey mate did you solve this issue already? https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1333

**Comment by mateusredfield** [comment]
After many tries one solution worked to me (although it caused a new flow in the code but its does not matter now). Just put the gradle under the phonegap version solved the problem.

` <preference name="phonegap-version" value="cli-5.2.0" />
   <preference name="android-build-tool" value="gradle" />`

 Anyway, thank you very much @jmaicaaan  and @raymondtam.
