### ISSUE TITLE
Any plans or opposition to merging forks?

### ISSUE THREAD

**Issue by mvdmakesthings** [Wizcorp/phonegap-facebook-plugin#1340]
I'm noticing that this repo isn't very active. There is a really good fork of this repo that has a lot of contributions that seem to address a lot of issues. https://github.com/jeduan/cordova-plugin-facebook4 Is there any opposition to reaching out to this fork owner and getting those contributions merged into the original repo?

**Comment by jacquesdev** [comment]
I suggest you just switch to that fork and use that - that is what I have been doing
