### ISSUE TITLE
facebookConnectPlugin is not defined

### ISSUE THREAD

**Issue by nikksan** [Wizcorp/phonegap-facebook-plugin#1347]
Really title says it all.
I install the plugin using 

> cordova plugin add https://github.com/jeduan/cordova-plugin-facebook4 --save --variable APP_ID="123456789" --variable APP_NAME="myApplication"

When the app runs on android I get the following error.
Btw, I`m new to cordova, how is this plugin supposed to work? The facebookConnectPlugin is not even injected in a controller?

**Comment by fquirogam** [comment]
same problem here. Did you find the solution?

**Comment by dnoliver** [comment]
This issue is related to https://github.com/jeduan/cordova-plugin-facebook4 (a fork of this project) report it there! I am closing this
