### ISSUE TITLE
Issues with iOS url scheme?

### ISSUE THREAD

**Issue by wturnerharris** [Wizcorp/phonegap-facebook-plugin#138]
Please bear with me as I'm new to iOS development. My Android Phonegap project works perfectly, but iOS however is less than operational. Phonegap 1.6.1 with jquery mobile 1.1.0 and latest fbconnect from github.

I've followed all the directions on the wiki of this project. Here is what occurs:
1. My app successfully initializes the plugin.
2. Since there is no fb installed on the emulator, the mobile safari window circles in with the facebook login dialog when the login button is clicked.
3. Once authenticated and the app is added to facebook's whitelist, the flow attempts to return to the app. It returns to the app's splash screen and then dims.
4. The app remains in this frozen state unless the hardware home key is pressed.
5. Clicking the app's icon to return to the app results in a native ios popup dialog with the fbXXXX://authorize/#access_token=xxx and an ok button.
6. Clicking ok successfully authenticates to facebook.

The problem here is the freeze, which occurs after the fb login dialog is accepted. I'm assuming this has something to do with the URL Scheme and Identifier. 

For clarity, Url Types has an Item 0, which contains the Url Identifier (value is the same as my Bundle Identifier value of com.examplesample.app) and the Url schemes with an Item 0 and the value is fbXXXX where XXXX is the facebook app id.

Hope this detail gives someone enough info to help me. Thanks!

**Comment by bitflower** [comment]
Hi, did you happen to use the Custom URL scheme plugin? If so, did you change it's javascript function call in the native code ? Or how did you achieve that Facebook and URL scheme work together? Thanks!
