### ISSUE TITLE
Plugin only works when native FB app is not installed (Android)

### ISSUE THREAD

**Issue by jensCocquyt** [Wizcorp/phonegap-facebook-plugin#263]
I've followed all the steps in the Android 'getting started' and everything works fine when I run the app on a device (emulator and real) that doesn't have the official Facebook app installed. When i run it on a device which has the official Facebook app installed and I click on the login button, the Facebook dialog appears and it asks for permission. I choose OK, the dialog disappears and nothing happens. No error or other alert appears and i'm not logged in neither.

Any ideas?

The javascript

```
    function logout() {
        FB.logout(function(response) {
                  alert('logged out');
                  });
    }


    function logIn() {

         try {
              FB.init({ appId: "*****************", nativeInterface: CDV.FB, useCachedDialogs: false });

              } catch (e) 
              {
              alert("error");
              }

        FB.login(
                 function(response) {
                 if (response.authResponse) { 

                  // not invoked
                  alert('logged in');      


                 } else {
                  // not invoked
                 alert('error');
                 }
                 },
                 { scope: "email" }
                 );
```

**Comment by mailtoamirjohn** [comment]
I am getting the same issues,

I don't know what I missed, please check following link for more details

http://stackoverflow.com/q/40087845/3600674
