### ISSUE TITLE
NullPointerException thrown after login 

### ISSUE THREAD

**Issue by ab2bc** [Wizcorp/phonegap-facebook-plugin#315]
Hello,

I'm trying to runt he HackBook example but cannot get past the login screen. My app launches just fine and I'm asked for granting permissions to the app after touching the Login button. Right after my app crashes with the following exception:

E/AndroidRuntime(25099): java.lang.RuntimeException: Unable to resume activity {com.facebook.hackbook/com.facebook.hackbook.HackBook}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=64206, result=0, data=Intent { (has extras) }} to activity {com.facebook.hackbook/com.facebook.hackbook.HackBook}: java.lang.NullPointerException
E/AndroidRuntime(25099):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2458)
E/AndroidRuntime(25099):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2486)
E/AndroidRuntime(25099):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2000)
E/AndroidRuntime(25099):    at android.app.ActivityThread.access$600(ActivityThread.java:128)
E/AndroidRuntime(25099):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1161)
E/AndroidRuntime(25099):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(25099):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(25099):    at android.app.ActivityThread.main(ActivityThread.java:4514)
E/AndroidRuntime(25099):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(25099):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(25099):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
E/AndroidRuntime(25099):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
E/AndroidRuntime(25099):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(25099): Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=64206, result=0, data=Intent { (has extras) }} to activity {com.facebook.hackbook/com.facebook.hackbook.HackBook}: java.lang.NullPointerException
E/AndroidRuntime(25099):    at android.app.ActivityThread.deliverResults(ActivityThread.java:2994)
E/AndroidRuntime(25099):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2445)
E/AndroidRuntime(25099):    ... 12 more
E/AndroidRuntime(25099): Caused by: java.lang.NullPointerException
E/AndroidRuntime(25099):    at org.apache.cordova.DroidGap.onActivityResult(DroidGap.java:858)
E/AndroidRuntime(25099):    at android.app.Activity.dispatchActivityResult(Activity.java:4649)
E/AndroidRuntime(25099):    at android.app.ActivityThread.deliverResults(ActivityThread.java:2990)

I'm running PhoneGap 2.7.0

Bests,

Yoanis.

**Comment by truetechchandru** [comment]
same issue I'm also got can any pls hellp
