### ISSUE TITLE
handleStatusChange always returns "unknown status" before "connected status"

### ISSUE THREAD

**Issue by shuffledex** [Wizcorp/phonegap-facebook-plugin#320]
Hey buddies!
I'm developing a simple app for Android OS.
Following the examples, when the user starts the app, the first code that I execute is:

```
    FB.init({
        appId: 'xxx',
        nativeInterface: CDV.FB,
        useCachedDialogs: false
    });

    FB.Event.subscribe('auth.statusChange', handleStatusChange);
    FB.getLoginStatus(handleStatusChange);
```

And my "Handle status" funcion is:

function handleStatusChange(response) {
    if (response.status === 'connected') {
        console.log('dashboard');
    } else if (response.status === 'not_authorized') {
        console.log('login');
    } else { // status unknown
        console.log('unknown');
    }
}

When I see the console log, the flow is always the same: first 'unknown', and then 'login' (when the user is already login in the app, of course)

Why this happens?

Thanks!

**Comment by mypetertw** [comment]
> In case it's helpful, or for anyone else Googling, I'm pretty sure this is because you have "block third party cookies" checked in Chrome Settings > Advanced Settings > Privacy > Content Settings. I wrote about this as part of another FB question here: http://stackoverflow.com/questions/25819058/facebook-noauthorizationerror-after-passing-signed-parameters-manually

I got a same issue and Allow all cookies but it still not working
