### ISSUE TITLE
FB.getLoginStatus is showing that I'm connect, but I'm not.

### ISSUE THREAD

**Issue by ghost** [Wizcorp/phonegap-facebook-plugin#401]
What can it be? When I launch my application, it verifies if the user is logged on facebook, but if I'm not connected, the above function shows show me that I'm connected.

**Comment by edmondchui** [comment]
Is it possible to change the API 

```
getLoginStatus(Function success, Function failure)
```

to

```
getLoginStatus(boolean refresh, Function success, Function failure)
```

to force a server trip to refresh the cached response as mention in this [Facebook documentation](https://developers.facebook.com/docs/reference/javascript/FB.getLoginStatus#servers)?
