### ISSUE TITLE
Sorry, something went wrong

### ISSUE THREAD

**Issue by rakanalh** [Wizcorp/phonegap-facebook-plugin#43]
Hello,

I followed all the instructions of how to use this plugin, i got my android hash key from my keystore and added it on facebook and installed my app's apk. Once i call FB.login i am redirected to a page on facebook where it says:

"Sorry, something went wrong."
"We're working on getting this fixed as soon as we can."

What am i doing wrong here?

**Comment by roysG** [comment]
i get this message on ios version 3.8, when the user is already approved the app, and try log in again with his facebook.

any updates ?
