### ISSUE TITLE
Plugin doesn't work on Android

### ISSUE THREAD

**Issue by zelphir** [Wizcorp/phonegap-facebook-plugin#432]
Using cordova 3.4.0-0.1.3, Android 4.4.2.

On iOS it is perfect, no problems, not able to make it working on android, I always get an error:

[ERROR] Error initialising Cordova: Class not found

![screen shot 2014-04-03 at 15 57 53](https://cloud.githubusercontent.com/assets/2644782/2605039/67386ce0-bb40-11e3-911a-720a0005b5b3.png)

**Comment by francoro** [comment]
Use this https://github.com/jeduan/cordova-plugin-facebook4 it has all the android sdk problems solved
