### ISSUE TITLE
No method to get publish_actions permission on Android

### ISSUE THREAD

**Issue by apbarros** [Wizcorp/phonegap-facebook-plugin#456]
If I'm not mistaken, based on the current methods available from the plugin on Android, there's no way to get publish_actions permissions...is that right or am I reading something wrong in the readme?It says the graph API is only available to iOS, and Login doesn't accept publish_actions anymore...

**Comment by nitinkothwal** [comment]
How can I get "publish_actions permissions"? I am getting this error "(200) Requires extended permission: publish_actions"
