### ISSUE TITLE
How to add like button to my app?

### ISSUE THREAD

**Issue by eswarreddy43** [Wizcorp/phonegap-facebook-plugin#494]
I am trying to implement like button functionality in my app. Whenever user likes my facebook page, user will get rewards. So i have tried to implement this like button functionality as described here:
https://developers.facebook.com/docs/plugins/like-button

But if user clicks on like button it will open login page, after entering the credentials its displaying blank page with in the app only. Next if i reopen the app, i am not getting the callbacks on like button click.

I went through the code and found following code at line **12660** in file **facebook-js-sdk.js** for like box:

``` javascript
FB.subclass('XFBML.LikeBox', 'XFBML.EdgeWidget', null, {

/* Method/Class definition*/


});

```

But I am not getting how exactly use this code and also listens for the event when user likes the page?

Any suggestions on implementing and tracking like page activity in phonegap/cordova  app?

**Comment by andrewb273** [comment]
Thanks for the guide, though I think it needs to clearly specify that the methodology requires publish_actions permission, which isn't ideal. Also the link to "How do I Add a Like Button?" isn't working as the id is `user-content-how-do-i-add-a-like-button`, whilst the anchor tag link is just `#how-do-i-add-a-like-button`. Is there a way I can make these changes to help out?

Also going to be exploring a potential solution that uses an iframe, if it's a clean method I may describe it here.

Lastly tagging that this issue is basically identical to #378.

**Comment by aogilvie** [comment]
https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/TROUBLESHOOTING.md#how-do-i-add-a-like-button

https://github.com/Wizcorp/phonegap-facebook-plugin/blob/develop/TROUBLESHOOTING.md#how-do-i-add-a-like-button

@andrewb273 are you sure?

**Comment by andrewb273** [comment]
@aogilvie Sorry yeah that was a mistake on my behalf.

Though I still think that on the FAQ, it should mention the need to get publish_actions.

**Comment by aogilvie** [comment]
@andrewb273 Updated: https://github.com/Wizcorp/phonegap-facebook-plugin/blob/develop/TROUBLESHOOTING.md

**Comment by andrewb273** [comment]
@aogilvie Great, thanks!

**Comment by andrewb273** [comment]
@aogilvie I've implemented a decent FB Like functionality in my phonegap project, and I thought I'd share a few findings. Perhaps just to provide more useful info in TROUBLESHOOTING.md, perhaps to provide a more advanced JS interface, or preferably inspire building Like functionality into the plugin!

1. GET (checking if a URL has been liked)
If URL isn't an existing FB object, it returns an error (I think 400, though could be 500). Though if this is the cause for the error, then JSON.parse(responseText).error.message will contain the string 'is not a valid object'

2. POST (liking an object)
If object doesn't exist, it will create it. Though if all you provide is the URL e.g. &object={encodeURIComponent(likeUrl)} - then it will return an error about varying missing fields. However the object will still be created, though not Liked. So if POST fails, it should be tried again. Second attempt worked reliably for liking new URLs.

3. DELETE (unliking an object) - no issues

Performance-wise, GET is ok but POST is a little slow. Too slow to not have the UI change upon starting a Like, whether it be a Loading state or assume success and alert if fails.

I've built a nice JS module to keep all this code out of my JS controllers, let me know if you'd like to see it. May be useful if this repo embarks on making an easy interface for Like.

**Comment by gastonbesada** [comment]
@andrewb273 @bgaillard Hi men, I'm a little confused, could you post an example how to implement it?
As I can see facebookConnectPlugin.api make GET request always. How can I make a POST request?
Thanks!

**Comment by gastonbesada** [comment]
@andrewb273 @bgaillard I think you are trying to say that we should use facebookConnectPlugin.api for know if the object is already liked by the user, then, if no, use a standard POST with graph URL. This way is working for me. But it will better if facebookConnectPlugin.api had an extra parameter with the kind of HTTPMethod, like: `facebookConnectPlugin.api(String requestPath, String requestType, Array permissions, Function success, Function failure)` where "requestType" could be GET or POST.
FB iOS SDK example:
```
[FBRequestConnection startWithGraphPath:@"/me"
                             parameters:nil
                             HTTPMethod:@"GET"
                      completionHandler:^(
                          FBRequestConnection *connection,
                          id result,
                          NSError *error
                      ) {
                          /* handle the result */
                      }];
```
FB Android SDK example:
```
new Request(
    session,
    "/me",
    null,
    HttpMethod.GET,
    new Request.Callback() {
        public void onCompleted(Response response) {
            /* handle the result */
        }
    }
).executeAsync();
```

**Comment by andrewb273** [comment]
@gastonbesada Didn't actually think of that as I've mainly been using direct Graph API requests using AJAX. Fair point though, facebookConnectPlugin.api() needs to be able to support POSTs given that FB.api() [supports POST](https://developers.facebook.com/docs/javascript/reference/FB.api).

**Comment by conantp** [comment]
Hey - based on what I'm seeing in the Facebook Docs and Graph API Explorer, it doesn't seem that I can like a "Page" using the Open Graph API - has anyone else experienced this?

I'm able to post a "like" action for other types of objects no problem, but I'm trying to confirm if this is a restriction for Facebook or if I'm just missing something. Might be good to add to the Troubleshooting.md document if that is the case. 

I'm testing this by doing a POST using the format:

https://graph.facebook.com/me/og.likes?access_token=FB_ACCESS_TOKEN&object=URL_TO_LIKE
