### ISSUE TITLE
Delete request does not work

### ISSUE THREAD

**Issue by hsmith825** [Wizcorp/phonegap-facebook-plugin#506]
I tried to delite request using the following method both logged in as the receiver of the request and sender:
facebookConnectPlugin.api(requestid+'_' +fbuserid +'/?access_token=' +fbuserid,success, fail);  I have also tried with the access token = app access token.  If I putin the receiver's access token, I get an object of the request.  If I use the sender's access token I get a display of the Graph Path only.  In no case is the request deleted.

You comments are appreciated.

**Comment by yarontt** [comment]
+1 for this.
I'm using it PGB as 
 <gap:plugin name="com.phonegap.plugins.facebookconnect" version="0.9.0">

It shouldn't be too hard to add support for all HTTP operations.
