### ISSUE TITLE
java.lang.NoClassDefFoundError: com.facebook.android.R$layout

### ISSUE THREAD

**Issue by neuberoliveira** [Wizcorp/phonegap-facebook-plugin#537]
I getting this error: java.lang.NoClassDefFoundError: com.facebook.android.R$layout

When i call:
facebookConnectPlugin.login(["basic_info"],
    function(){ alert("Success") },
    function () { alert(":(") }
);

07-02 20:25:53.577: D/HAWAII_EGL(18108): eglMakeCurrent(0x4fced2d0, 0x4fced2f0, 0x4fced2f0) Thread: 18108
07-02 20:25:53.717: V/WebViewInputDispatcher(18108): blockWebkitDraw
07-02 20:25:53.717: V/WebViewInputDispatcher(18108): blockWebkitDraw lockedtrue
07-02 20:25:54.047: D/webview(18108): blockWebkitViewMessage= false
07-02 20:25:54.167: D/ConnectPlugin(18108): login FB
07-02 20:25:54.217: W/dalvikvm(18108): VFY: unable to resolve static field 2311 (com_facebook_internet_permission_error_title) in Lcom/facebook/android/R$string;
07-02 20:25:54.217: D/dalvikvm(18108): VFY: replacing opcode 0x60 at 0x0010
07-02 20:25:54.227: I/dalvikvm(18108): DexOpt: unable to optimize static field ref 0x0906 at 0x18 in Lcom/facebook/AuthorizationClient;.checkInternetPermission
07-02 20:25:54.378: W/dalvikvm(18108): VFY: unable to resolve static field 2301 (com_facebook_login_activity_layout) in Lcom/facebook/android/R$layout;
07-02 20:25:54.378: D/dalvikvm(18108): VFY: replacing opcode 0x60 at 0x0003
07-02 20:25:54.378: W/dalvikvm(18108): VFY: unable to resolve static field 2284 (com_facebook_login_activity_progress_bar) in Lcom/facebook/android/R$id;
07-02 20:25:54.378: D/dalvikvm(18108): VFY: replacing opcode 0x60 at 0x0008
07-02 20:25:54.498: D/dalvikvm(18108): GC_CONCURRENT freed 532K, 18% free 8838K/10748K, paused 4ms+7ms, total 46ms
07-02 20:25:54.588: D/CordovaActivity(18108): Paused the application!
07-02 20:25:54.588: D/CordovaWebView(18108): Handle the pause
07-02 20:25:54.588: D/WebView(18108): loadUrlImpl: called
07-02 20:25:54.648: W/PluginManager(18108): THREAD WARNING: exec() call to FacebookConnectPlugin.login blocked the main thread for 480ms. Plugin should use CordovaInterface.getThreadPool().
07-02 20:25:54.748: D/webcore(18108):  CORE loadUrl: called
07-02 20:25:54.748: D/webkit(18108): Firewall not null
07-02 20:25:54.748: D/webkit(18108): euler: isUrlBlocked = false
07-02 20:25:54.908: D/AndroidRuntime(18108): Shutting down VM
07-02 20:25:54.908: W/dalvikvm(18108): threadid=1: thread exiting with uncaught exception (group=0x420af930)
07-02 20:25:54.938: E/AndroidRuntime(18108): FATAL EXCEPTION: main
07-02 20:25:54.938: E/AndroidRuntime(18108): java.lang.NoClassDefFoundError: com.facebook.android.R$layout
07-02 20:25:54.938: E/AndroidRuntime(18108):    at com.facebook.LoginActivity.onCreate(LoginActivity.java:57)
07-02 20:25:54.938: E/AndroidRuntime(18108):    at android.app.Activity.performCreate(Activity.java:5326)
07-02 20:25:54.938: E/AndroidRuntime(18108):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
07-02 20:25:54.938: E/AndroidRuntime(18108):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2218)
07-02 20:25:54.938: E/AndroidRuntime(18108):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2309)
07-02 20:25:54.938: E/AndroidRuntime(18108):    at android.app.ActivityThread.access$700(ActivityThread.java:157)
07-02 20:25:54.938: E/AndroidRuntime(18108):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289)
07-02 20:25:54.938: E/AndroidRuntime(18108):    at android.os.Handler.dispatchMessage(Handler.java:99)
07-02 20:25:54.938: E/AndroidRuntime(18108):    at android.os.Looper.loop(Looper.java:176)
07-02 20:25:54.938: E/AndroidRuntime(18108):    at android.app.ActivityThread.main(ActivityThread.java:5317)
07-02 20:25:54.938: E/AndroidRuntime(18108):    at java.lang.reflect.Method.invokeNative(Native Method)
07-02 20:25:54.938: E/AndroidRuntime(18108):    at java.lang.reflect.Method.invoke(Method.java:511)
07-02 20:25:54.938: E/AndroidRuntime(18108):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
07-02 20:25:54.938: E/AndroidRuntime(18108):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
07-02 20:25:54.938: E/AndroidRuntime(18108):    at dalvik.system.NativeStart.main(Native Method)

**Comment by hejie** [comment]
Caused by: java.lang.NoClassDefFoundError: com.facebook.drawee.R$styleable
                                                                   at com.facebook.drawee.view.GenericDraweeView.inflateHierarchy(GenericDraweeView.java:128)
                                                                   at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:77)
                                                                   at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:60)
                                                                   at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:600) 
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:354)

**Comment by HildaChen** [comment]
I meet the same problem
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="com.example.testsimpledraweeview.MainActivity" >

```
 <com.facebook.drawee.view.SimpleDraweeView
    android:id="@+id/baseline_jpeg"
    android:layout_width="400dp"
    android:layout_height="400dp" />
```

</RelativeLayout>

```
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    Fresco.initialize(this);
    com.facebook.drawee.view.SimpleDraweeView view = (SimpleDraweeView) findViewById(R.id.baseline_jpeg);
    view.setImageURI(Uri.parse("http://pic9.qiyipic.com/common/20160104/90df5a9aa2804057be1a7f3df5e31825.jpg"));
}
```
