### ISSUE TITLE
'FacebookSDK/FacebookSDK.h' file not found

### ISSUE THREAD

**Issue by Moussawi7** [Wizcorp/phonegap-facebook-plugin#545]
I already installed the latest version of phonegap-facebook-plugin But when i build the project, I got the error message below. 

com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m:11:
Et3arrafApp/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.h:11:9: fatal error:
      'FacebookSDK/FacebookSDK.h' file not found
# import <FacebookSDK/FacebookSDK.h>

```
    ^
```

1 error generated.

*\* BUILD FAILED **

The following build commands failed:
    CompileC build/Et3arrafApp.build/Debug-iphonesimulator/Et3arrafApp.build/Objects-normal/i386/FacebookConnectPlugin.o Et3arrafApp/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: /Users/apple/Desktop/et3arraf/platforms/ios/cordova/build: Command failed with exit code 65
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Process.ChildProcess._handle.onexit (child_process.js:820:5)

**Comment by yarontt** [comment]
Any way to solve this issue on Phonegap Build?

**Comment by gulfcoastdev** [comment]
I followed the instructions from the:
https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/platforms/ios/README.md
But it still gives me an error 'FacebookSDK' file not found

**Comment by gulfcoastdev** [comment]
I also tried:
-dragging the framework manually to the Frameworks group in Xcode 
-adding it to the build phases
Nothing worked for me so far.
