### ISSUE TITLE
Phonegap Build "facebookConnectPlugin is not defined" error (only 0.4.0 is available on phonegap build)

### ISSUE THREAD

**Issue by jackychow** [Wizcorp/phonegap-facebook-plugin#578]
This happens on android for me (am only testing android). 
local build with plugin install works with no problem. 
Using adobe phonegap build and specified version to 0.4.0, build was successful, phonegap build also detected facebookconnect plugin installed, but got "facebookConnectPlugin is not defined" when using it. Is this a version problem? I realize the plugin object was FacebookConnectPlugin (capital F) before. is the phonegap build version 0.4.0 the current version in master?

**Comment by anuragrath** [comment]
Any update on this?
Thanks,

**Comment by jfaris** [comment]
@anuragrath See #839 - tldr: PhoneGap Build can't be supported any more.  You can reference the version in the cordova plugin registry but iOS builds won't work.
