### ISSUE TITLE
sending message

### ISSUE THREAD

**Issue by Likon84** [Wizcorp/phonegap-facebook-plugin#593]
Hi

Is there a possibility to send private message using plugin?
I see there is such a future in facebook documentation but I don't see it in plugin.
If no than why?

**Comment by sunshineo** [comment]
I tried this. Works. I jump from my app to Facebook messenger. However, for the web version, I can easily specify a "to" field and pre-fill the receiver. But here I don't think I can. I read https://developers.facebook.com/docs/android/share#message-dialog and it seems that there is no such function from Facebook's side. Bummer.
Does anyone have some other information?
