### ISSUE TITLE
Windows tip about Android key hash

### ISSUE THREAD

**Issue by fernandomatos** [Wizcorp/phonegap-facebook-plugin#60]
Hi guys, 

Windows users have to be careful about openssl-for-windows (http://code.google.com/p/openssl-for-windows/downloads/list), the latest version, at least on plataform 64bits, don't generate the correct hash that Facebook need it for android apps.

When we are using this plugin we need provide a security hash to the facebook, in our aplication page (https://developers.facebook.com/apps), if what i'm saying don't make sense for you I recomend you read these materials:
http://developers.facebook.com/docs/mobile/android/build/#sig
http://developer.android.com/guide/publishing/app-signing.html

If you've read these materials and already know how works and how you will have to do to generate your security hash to use this plugin, remember of this tip:

Use one of this versions: openssl-0.9.8e_X64.zip or openssl-0.9.8d_X64.rar

You should not use the openssl-0.9.8k_X64.zip.

I hope this tip be useful. I lost a lot of time, testing ways to generate the correct hash and in the end the problem was with the latest version of openssl.

**Comment by chaunvbka** [comment]
thanks you very much. I also lost a lot of time with this problem.

**Comment by mladenp** [comment]
You should be careful when entering alias/password because they can't be checked if they match and wrong hash can be easily generated. 
I just spent hours figuring out what's wrong it turned out not only did i have that "wrong" openssl on windows but i also typed wrong alias.

**Comment by netvillage** [comment]
Is this still a problem with the newer 1.x versions?

**Comment by biplovsubedi** [comment]
Just wanted to say that you very much. It is 2020 and even after 9 years, this problem still persists. To make matter worse, openssl-0.9.8k_X64.zip is provided as (featured) in openssl downloads page. Therefore, more people are likely to have this problem.

**Comment by fernandomatos** [comment]
This is really wonderful about the GitHub community, developers help each other and some things remain helping for a decade. This post taught me a very important life lesson in my 20s, now I'm 30 and it still does.

**Comment by godgege** [comment]
Thank you very much! It's too difficult to check this problem. Thank you for your research

**Comment by Uthayakumar-R** [comment]
Thank you very much
