### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by csoare7** [Wizcorp/phonegap-facebook-plugin#600]
Hi, thanks for the awesome plugin! I was able to get it working on both ios and android, however on the webapp I am struggling to make it work.

I am using Ionic and followed exactly the instructions, copied the  facebookConnectPlugin.js in my js folder and get that error:

Uncaught TypeError: Cannot read property 'appendChild' of null on line 174.

Any ideas why that would be?

Posted also on stack:

http://stackoverflow.com/questions/25068844/phonegap-facebook-plugin-on-webapp-js-error

**Comment by manihere** [comment]
thanks @panickz worked flawlessly :)
