### ISSUE TITLE
facebookConnectPlugin.login doesn't call neither success nor faillure methods

### ISSUE THREAD

**Issue by MantasR** [Wizcorp/phonegap-facebook-plugin#618]
Hi, what I am doing wrong?
I call this method:
facebookConnectPlugin.login(["email"],
        function (error) { console.log("THIS IS AN WIN FROM FB: " + error); openDialogFB(); },
        function (error) { console.log("THIS IS AN ERROR FROM FB: " + error); }
    );

**Comment by batman11111** [comment]
I'm having the same issue.  Using phonegap build for an IOS app.  When I use facebookConnectPlugin.login  the screen switches over to the facebook app and then my app restarts.  I never receives a success or fail call back and dont get any error messages. What causes this? What can I try to track down this issue?

**Comment by tkuben** [comment]
Anyone get to the bottom of this issue? I am seeing this behaviour on ios 9 where a success/failure facebook login is not calling the callback function. Cordova version: 5.4.1

```
 facebookConnectPlugin.login(["public_profile", "email"], 
               function(response) {
             console.log("FACEBOOK CALLED"); 
             console.log(response); 
            }, 
            function(error) {
                console.log("FACEBOOK ERROR CALLED"); 
                console.log("Error");   
            }
         );
```

Cheer,s 
TJ

**Comment by michelevirgilio** [comment]
+1

**Comment by jacksonkr** [comment]
I was having this problem too. Ionic / cordova is tricky business sometimes.

I was getting no feedback on the safari console, but my functionality wasn't working anymore.

Reading the posting guidelines for issues on this code I looked at my xcode logs:

```
2017-03-12 10:48:26.405666 ratl[21855:4728921] CDVPlugin class FacebookConnectPlugin (pluginName: FacebookConnectPlugin) does not exist.
2017-03-12 10:48:26.405898 ratl[21855:4728921] ERROR: Plugin 'FacebookConnectPlugin' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2017-03-12 10:48:26.406633 ratl[21855:4728921] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["FacebookConnectPlugin907726271","FacebookConnectPlugin","login",["public_profile","email"]]
```

When I added/removed the plugin (or the ios platform) something got junked in my xcode search paths and now the plugin was no longer found. After spending too much time in `build settings > framework search paths` AND `build phases > link binary with libraries` I decided to do all my framework linking with `framework search paths`

There's going to be a more efficient way, but I'm just looking for a solution this morning. Here's what I have:
```
$(PROJECT_DIR)/ratl/Plugins/cordova-plugin-facebook4; non-recursive
$(PROJECT_DIR)/ratl/Plugins/phonegap-facebook-plugin; non-recursive
```

I wanted to go with `$(PROJECT_DIR); recursive` but I have two copies of the facebook sdk which is causing duplicate errors.

Cheers!
