### ISSUE TITLE
After logging out Facebook App, .getLoginStatus still returns "connected"

### ISSUE THREAD

**Issue by basicallydan** [Wizcorp/phonegap-facebook-plugin#620]
I logged in a user to my app using Facebook, all good and fine there. But when I log out the user from the Facebook app, and go back to my app, when I check the status coming back from `.getLoginStatus(Function success, Function error)` - and it says "connected" rather than "unknown" which is what I expected.

Is this expected behaviour? Am I doing this wrong?

Thanks.

**Comment by edmondchui** [comment]
Is it possible to change the API 

```
getLoginStatus(Function success, Function failure)
```

to

```
getLoginStatus(boolean refresh, Function success, Function failure)
```

to force a server trip to refresh the cached response as mention in this [Facebook documentation](https://developers.facebook.com/docs/reference/javascript/FB.getLoginStatus#servers)?

**Comment by vsymguysung** [comment]
@aogilvie  I have one question. When the FB session expires, how could I detect it in my app ? 

It seems that the `getLoginStatus` returns a cached value, I was not able to detect the session expiration.

**Comment by Maritims** [comment]
https://developers.facebook.com/docs/reference/javascript/FB.getLoginStatus

> To improve the performance of your application, not every call to check the status of the user will result in request to Facebook's servers. Where possible, the response is cached. The first time in the current browser session that FB.getLoginStatus is called, or the JS SDK is init'd with status: true, the response object will be cached by the SDK. Subsequent calls to FB.getLoginStatus will return data from this cached response.

**Comment by levi-20** [comment]
i m logged in but even though it returns null response

**Comment by nikse** [comment]
Even after passing true as the second parameter to get login status it is still returning me as connected on a page refresh. Using js api v 2.12, incognito + normal browser modes and not allowing fb to remember browser

Use case: login to my web page via facebook login button, click logout which calls FB.logout() (and subsequent calls to getLoginStatus return proper response before page refresh), refresh page and console.log what FB.getLoginStatus is returning and status is connected.

**Comment by jwbats** [comment]
It's now 3.5 years later, and I'm still experiencing this issue. Although I'm not using the phonegap fb plugin. This is an issue with fb js sdk. I'm posting it on the fb dev community forum soon.

**Comment by basicallydan** [comment]
I started this issue several years ago but I haven't used Phonegap in a long time now. I don't have the will to verify the fix that @aogilvie proposed I'm afraid. If anybody would like to, please feel free, but I'm going to close the issue for now.
