### ISSUE TITLE
Re-request permissions

### ISSUE THREAD

**Issue by asoyfer** [Wizcorp/phonegap-facebook-plugin#642]
The FB js api says you need to add    auth_type: 'rerequest' when re-requesting a permission like so:
FB.login(
  function(response) {
    console.log(response);
  },
  {
    scope: 'user_likes',
    auth_type: 'rerequest'
  }
);

Since the format for this plugin is:  facebookConnectPlugin.login(Array strings of permissions, Function success, Function failure)  where could I add "auth_type: 'rerequest"?   Or does it work diff because this talks to the underlying IOS and android SDK?

**Comment by jfurneaux** [comment]
I could be mistaken, but I don't believe that this is true. I believe that the request behaves as per Facebook's guidelines - rerequests are not processed without this specific parameter.

I'd suggest we need to add a 'rerequest' optional parameter for .login which sets permissionObj.auth_type = 'rerequest'.
