### ISSUE TITLE
api call me/friends doesn't work

### ISSUE THREAD

**Issue by NCS80** [Wizcorp/phonegap-facebook-plugin#643]
Hi,

I try to get al list of friends (using the app). 

this is my code:

```
facebookConnectPlugin.api("me/friends",
    function (result) {
        alert("Result: " + JSON.stringify(result));
    },
    function (error) {
        alert("Failed: " + error);
    });
```

this doesn't even gives an error...
I use Android, does this really only work on IOS?? 
in that case, is there another way to get the friends?

greets

**Comment by speedev196** [comment]
this is a lie.
