### ISSUE TITLE
Doc Update: Cannot make calls to facebookConnectPlugin.api in parallel?

### ISSUE THREAD

**Issue by rajatrocks** [Wizcorp/phonegap-facebook-plugin#674]
Great plugin! Just spent some time trying to figure out why my code was working fine in the desktop web browser, but wasn't when run on device emulators. It was because I had code that looked like: 

facebookConnectPlugin.api('/me' + qString, [], ...
facebookConnectPlugin.api('/me/friends', [], ...

Where two calls where being made in parallel. They appeared to be clobbering each other and their callbacks. Only one would get called and then things wouldn't process correctly. 

Putting the second call inside the success function of the first one (making the calls serially) fixed the issue. I may have missed this somewhere in the docs, but it might be worth adding a note about this if it's not already in there. 

Thanks!

**Comment by aogilvie** [comment]
@rajatrocks This should be fixed with https://github.com/Wizcorp/phonegap-facebook-plugin/pull/889

**Comment by rajatrocks** [comment]
Thanks @aogilvie !
