### ISSUE TITLE
facebookConnectPlugin.getLoginStatus userID null

### ISSUE THREAD

**Issue by NCS80** [Wizcorp/phonegap-facebook-plugin#698]
Hi, when I call 

```
facebookConnectPlugin.getLoginStatus(function(response) {
    console.log(JSON.stringify(response));
};)
```

I get the response 

```
{
    "authResponse" : {
        "userID" : "null",
        "accessToken" : "token...",
        "session_key" : true,
        "expiresIn" : "4912....",
        "sig" : "..."
    },
    "status" : "connected"
}
```

as you see, userID is null. When I use the login function I get a userID returned. 
I develop for Android.

any ideas?

thx in advance

**Comment by lrettig** [comment]
Hello

I'm having this same issue on iOS using the latest release code. I'm guessing it wasn't fixed on iOS here? Any tips?

Thanks
