### ISSUE TITLE
Cordova 3.6 - handleOpenUrl

### ISSUE THREAD

**Issue by jorgedavila25** [Wizcorp/phonegap-facebook-plugin#703]
Looks like Cordova 3.6 got rid of handleOpenUrl from the App Delegate, and it seems like this plugin needs it. Anyone have any insights on this?

**Comment by JackNova** [comment]
I had similar problems, in my case the solution was to make sure of following things:
- correct configuration in the app .plist (I was using a different bundle id for a test version of the app and this should be configured accordingly, I had to create a test version of the app on facebook where I configured the appropriate bundle id).
- if you have a test version of the fb app it should be either publicly available or it should have some test users configured through the ROLES tab of the app.
- for further insights refer to this StackOverflow question: http://stackoverflow.com/questions/23509386/facebook-sdk-on-ios-app-session-fixing/28673422#28673422
