### ISSUE TITLE
Posting OpenGraph Object

### ISSUE THREAD

**Issue by jkassis** [Wizcorp/phonegap-facebook-plugin#759]
How do I post an Open Graph API Story?

In Javascript on the web it looks like this...
FB.api('me/' + fbAppName + ':' + storyId, 'post', objects, respond);

The FacebookConnectPlugin is read only?

Obj-C:
- (void) makeGraphCall:(NSString *)graphPath

Javascript:
cordova.exec(respond, respond, "FacebookConnectPlugin",
                            "graphApi", [ 'me/' + fbAppName + ':' + storyId,
                                    permissions ], [ "publish_actions" ]);

**Comment by gabrielmancini** [comment]
i need post too, how i do?

**Comment by sunshineo** [comment]
+1 I just need to post to current user's wall without bring up the share dialog.

**Comment by thomasvbe** [comment]
Can it be that the share dialog with open graph stories only works in the web browser on your smart phone? Not in the native app?

**Comment by romuloctba** [comment]
+1 for opengraph posts support

**Comment by jkassis** [comment]
stale
