### ISSUE TITLE
Plugin does not work with the new "browser" platform in PhoneGap

### ISSUE THREAD

**Issue by rickdmer** [Wizcorp/phonegap-facebook-plugin#794]
Recently, [a new "browser" platform was added to PhoneGap](http://www.raymondcamden.com/2014/9/24/Browser-as-a-platform-for-your-PhoneGapCordova-apps)

A couple notes of things that may need to change:
- `window.cordova` is no longer a good way for checking if you are in the browser as this now exists in the browser platform. I ended up using something like `!window.cordova || (window.cordova && window.cordova.platformId === 'browser')`
- The browser code from `www/js/facebookConnectPlugin.js` will need to run on the browser platform. I achieved this by copying the if block from `www/js/facebookConnectPlugin.js` to the if block in `phonegap\plugin\facebookConnectPlugin\facebookConnectPlugin.js`.

I doubt this is the best way to fix the issue so I'm opening up a ticket so that someone with a better understanding of the project can take a stab at it.

**Comment by marcostrama** [comment]
Dont work here too. I copied cordova.js from browser do my www/js and included a IF to determine if cordova was defined.
