### ISSUE TITLE
Jar Mismatch

### ISSUE THREAD

**Issue by srameshr** [Wizcorp/phonegap-facebook-plugin#812]
I added the plugin, and now I get this error :

```
 ~/adt-bundle-linux/sdk/tools/ant/build.xml:577: Jar mismatch! Fix your dependencies.
```

```
[dependency] Found 2 versions of android-support-v4.jar in the dependency list,
[dependency] but not all the versions are identical (check is based on SHA-1 only at this time).
[dependency] All versions of the libraries must be the same at this time.
[dependency] Versions found are:
[dependency] Path: /home/siddharth/appTest/Madzz/ui/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/libs/android-support-v4.jar
[dependency]    Length: 758727
[dependency]    SHA-1: efec67655f6db90757faa37201efcee2a9ec3507
[dependency] Path: /home/siddharth/appTest/Madzz/ui/platforms/android/libs/android-support-v4.jar
[dependency]    Length: 987314
[dependency]    SHA-1: 9b6a9a9078af571732159b904ad423b03b7cc786

BUILD FAILED
/home/siddharth/Downloads/adt-bundle-linux/sdk/tools/ant/build.xml:577: Jar mismatch! Fix your dependencies

Total time: 1 second

/home/siddharth/appTest/Madzz/ui/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: debug,-f,/home/siddharth/appTest/Madzz/ui/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
Error: /home/siddharth/appTest/Madzz/ui/platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
```

Please have a look at this

**Comment by andrewb273** [comment]
Coming across this issue, however because I'm using [build.phonegap](http://build.phonegap.com/) I can't just delete stuff out of the lib folder. Dependency error occurs between latest releases for `com.phonegap.plugins.facebookconnect` and `nl.x-services.plugins.googleplus`. Error doesn't occur between version 0.4.0 of `facebookconnect` and the latest `googleplus`. So now I have to use the old `facebookconnect` version for Android builds, woohoo.

I'm guessing that it's the `googleplus` plugin with the old support jar ref, @aogilvie is `facebookconnect` using the latest main support jar release?

**Comment by aogilvie** [comment]
We have to use the version provided by Facebook's SDK. :/
You can try swapping it out but i've not had success building with other android-support-v4.jar. I thinks they modified it somehow T-T
https://github.com/facebook/facebook-android-sdk/tree/master/libs

Here's a thread on trying to add android-support-v4.jar as a dependency (sorry, still ongoing)
https://github.com/Wizcorp/phonegap-facebook-plugin/issues/750#issuecomment-62378369

**Comment by andrewb273** [comment]
@aogilvie hmm that's frustrating. I'm inexperienced with Android/Java development, so can't offer assistance unfortunately! We'll just wait by patiently.

**Comment by imaffett** [comment]
@andrewb273 I'll second this. I'm actually confused.  At one point @aogilvie did merge in the MobileChromeApps android-support-v4 in , but then upgraded it.  I told him the jar still worked fine.  We're having big problems with this in the Intel XDK because Android apps fail to build now.

**Comment by TheWyrm** [comment]
@aogilvie Yup, I also use the intel XDK and have this build error. :(

**Comment by mladenp** [comment]
I fixed this jar mismatch thing a month or so ago on an old project that used this plugin. But i can't remember what exactly i did. Support jar doesn't seems to be updated in this plugin.
I thought it was simple as copying one jar from android.support plugin to facebook plugin and inversely, but its not that.

**Comment by Eric85B** [comment]
Up.

I have the same problem using Phonegap Build. Is there a solution?

Thanks
