### ISSUE TITLE
facebookConnectPlugin.api( "/me/photos".......doesn't function

### ISSUE THREAD

**Issue by carlo1234** [Wizcorp/phonegap-facebook-plugin#821]
Hi 
With your old Facebook connect plugin (0.4.0) to publish a photo I did This:

```
    FB.api(
        "/me/photos",
        "POST",
        {
            "message": 'xxxxxxxxx',
            "url": imagefinal
        },
        function (response) {
            if (response && !response.error) {
                 alert('Ok')

            } else alert('Error');
        }
    );
```

But now I don't understand how can I publish (where I have to insert message and url, ecc)....Do you know how I can do it using the api and not showDialog?

**Comment by Mahesh93** [comment]
@aogilvie I used to publish photo function for that i am using multipart/form-data now it showing facebook error, If my multipart/form data is in wrong format then please suggest me how can i send image with multiform data,

facebookConnectPlugin.showDialog( 
    {
        method: "feed",
        source: image,
        name:'Test Post',
        message:'First photo post',  
        caption: 'Testing using phonegap plugin',
        description: 'Posting photo using phonegap facebook plugin'
    }, 
    function (response) { alert(JSON.stringify(response)) },
    function (response) { alert(JSON.stringify(response)) });

var image = "data:multipart/form-data;base64," + " string from CAMERA_DATA URI

And please clarify me Am I sent the correct image or not, I want to get photo from device and share on facebook

Thanks in Advance

**Comment by mdanics** [comment]
@aogilvie can this be done now?
