### ISSUE TITLE
errorMessage Facebook error: Session was closed and was not closed normally

### ISSUE THREAD

**Issue by batman11111** [Wizcorp/phonegap-facebook-plugin#826]
I am using phonegap build to build an app for android and Im getting the above error message when trying to run this code: facebookConnectPlugin.login( ["email"],
                    function (response) { alert(JSON.stringify(response)) },
                    function (response) { alert(JSON.stringify(response)) });
            }
What causes this error? I've created a new hash, uploaded it to facebook and phonegap build and still the same error.  Any pointers in the right direction would be appreciated!

**Comment by artistika** [comment]
batman11111 do i have to remove it from my fb apps in order to solve the error or it will disappear instantly after changing the display name with the namespace?

**Comment by artistika** [comment]
when i change the display name into namespace and build the app, then in the facebookconnect.xml is generated another row with the display name...

<?xml version='1.0' encoding='utf-8'?>
<resources>
    <string name="fb_app_id">id</string>
    <string name="fb_app_name">namespace</string>
    <string name="fb_app_name">display name</string>
</resources>

**Comment by batman11111** [comment]
Sounds like you may be using cordova? I used phonegap build, im not really familiar with Cordova. 

Sent from Yahoo Mail on Android

**Comment by raoulcimpean** [comment]
Problem is with key has. If you have Android Studio installed and you can see logcat when you try to login there will be an error. In that error will be a key has which must be added in facebook app.

**Comment by manasthe** [comment]
i did add the hash key but still the same problem occures

**Comment by Simerjit-developer** [comment]
Will you please let me know the format to write id,namespace,display name in the config.xml file?

**Comment by ashutoshdev-zz** [comment]
cordova facebook plugin com.facebook.FacebookAuthorizationException: Session was closed and was not closed normally

**Comment by bobibt** [comment]
@ashutoshdev The problem is the key hash. You should generate key hash on the computer that you are building the app with and then insert it on Facebook Developers dashboard.

**Comment by bobibt** [comment]
@Simerjit-developer https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/platforms/android/README.md
Install the latest version of the plugin and everything will be filled correctly in the config.xml.

**Comment by Simerjit-developer** [comment]
Thanks for the reply @bobibt In the installation, 
For Android sample app remember to configure the project with your FB app id in the res/values/facebookconnect.xml file. For example:

```
<resources>
    <string name="fb_app_id">123456789</string>
    <string name="fb_app_name">TEST</string>
</resources>
```

but I didn't found "/facebookconnect.xml" in android platform plugin.

**Comment by Simerjit-developer** [comment]
I generate keyhash using:

`keytool -exportcert -alias androiddebugkey -keystore %HOMEPATH%\.android\debug.keystore | openssl sha1 -binary | openssl base64`

still getting same error.

"E/ConnectPlugin: com.facebook.FacebookAuthorizationException: Session was closed and was not closed normally"

**Comment by bobibt** [comment]
@Simerjit-developer The facebookconnect.xml file is in platforms/android/res/values/facebookconnect.xml

**Comment by Simerjit-developer** [comment]
I add the plugin from starting, generating hash key, still getting the same error.. 
I have a question too @bobibt Is it work before on google playstore(i.e. Testing)

**Comment by bobibt** [comment]
@Simerjit-developer You need to insert both debug and release hash keys. You can't test release version of the apk with debug key hash.

**Comment by kossanah** [comment]
Hello,
The last time I had this error, I found out i used  the wrong password
while generating debug hash key using android keytool.
Make sure to used password as "android"

**Comment by raoulcimpean** [comment]
Hi,
You must have  a soft where you can see logcat android . In logcat it will throw an error: bla bla you must use this haxh key : 213123213 . 
I used Android Studio , i create an empty project,to can see logcat,and then with device connected , there you can see errors from plugins.From java code.Do this,copy hash key from logcat,and it will work 100%.

**Comment by amitbindal09** [comment]
Hi All, I was also getting same error. I tried different versions of Openssl and 0.9.8e worked for me.

Here https://code.google.com/archive/p/openssl-for-windows/downloads you can find three different versions of openssl with 32 bit or 64 bit operating system. Try all for generating key hash, i hope it will work for you also. Thanks!

**Comment by ashutoshdev-zz** [comment]
Thanks @bobibt

**Comment by MohDahshan** [comment]
you might not make your facebook App live..
