### ISSUE TITLE
phonegap build iOS  failure, no such file or directory: Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m

### ISSUE THREAD

**Issue by mcacciottolo** [Wizcorp/phonegap-facebook-plugin#830]
I have been encountering this error and have not been able to resolve it. When building my app using phonegap build, the Android builds successfully and functions perfectly. However, iOS fails with the error listed below. 

Here is a snippet from the config.xml in regards to the plugin:

```
<gap:plugin name="com.phonegap.plugins.facebookconnect" version="0.9.0">
    <param name="APP_ID" value="<MY APP ID>" />
    <param name="APP_NAME" value="<MY APP NAME>" />
</gap:plugin>
<preference name="phonegap-version" value="3.6.3"/>
```

Any help would be greatly appreciated!

CompileC build/gbot.build/Release-iphoneos/gbot.build/Objects-normal/armv7/FacebookConnectPlugin.o gbot/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DCORDOVA_FRAMEWORK=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=6.0 -iquote /project/build/gbot.build/Release-iphoneos/gbot.build/gbot-generated-files.hmap -I/project/build/gbot.build/Release-iphoneos/gbot.build/gbot-own-target-headers.hmap -I/project/build/gbot.build/Release-iphoneos/gbot.build/gbot-all-target-headers.hmap -iquote /project/build/gbot.build/Release-iphoneos/gbot.build/gbot-project-headers.hmap -I/project/build/include -I/project/build/usr/local/lib/include -I/project/build/UninstalledProducts/include -I/project/build -I/project/build/gbot.build/Release-iphoneos/gbot.build/DerivedSources/armv7 -I/project/build/gbot.build/Release-iphoneos/gbot.build/DerivedSources -F/project/build -Fcordova/plugins/com.phonegap.plugins.facebookconnect/platforms/android/res/xml/Plugins/com.phonegap.plugins.facebookconnect -include /var/folders/8r/065_jhkn1qqf03lr71kjj6480000gp/C/com.apple.DeveloperTools/6.1-6A1052d/Xcode/SharedPrecompiledHeaders/gbot-Prefix-fwplkxvwcbywxbbkrrbxqngqenoo/gbot-Prefix.pch -MMD -MT dependencies -MF /project/build/gbot.build/Release-iphoneos/gbot.build/Objects-normal/armv7/FacebookConnectPlugin.d --serialize-diagnostics /project/build/gbot.build/Release-iphoneos/gbot.build/Objects-normal/armv7/FacebookConnectPlugin.dia -c /project/gbot/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m -o /project/build/gbot.build/Release-iphoneos/gbot.build/Objects-normal/armv7/FacebookConnectPlugin.o
clang: error: no such file or directory: '/project/gbot/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

*\* BUILD FAILED **

The following build commands failed:
    CompileC build/gbot.build/Release-iphoneos/gbot.build/Objects-normal/armv7/FacebookConnectPlugin.o gbot/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by brodybits** [comment]
Same issue observed on sqlite plugin, now reported in phonegap/build#431
