### ISSUE TITLE
problem with facebookconnectplugin.api

### ISSUE THREAD

**Issue by batman11111** [Wizcorp/phonegap-facebook-plugin#833]
Can you give me an example of how to use facebookConnectPlugin.api?  I've used the "get birthday" example at the bottom of the main page and I can't get it to work. No errors, it just doesn't do anything. The log in, log out, get status, show a dialog... all that stuff works, just not the .api

I've also tried:

facebookConnectPlugin.api ('/me', {fields: 'last_name'}, function(response) {
  console.log(response);
}); //straight from facebooks website and it still doesn't work

If you can tell me how to get a persons first name from their profile that would be a tremendous help.  (or any other data that doesn't require special permissions)

**Comment by elshorbagy** [comment]
would someone please help me to make the login work correctly?
Thanks
