### ISSUE TITLE
Plugin works differently for web and for android

### ISSUE THREAD

**Issue by nitishmehta** [Wizcorp/phonegap-facebook-plugin#837]
I am doing a 
> facebookConnectPlugin.login(["email","public_profile"], function(response) { 
//check for permissions
 }

and then inside the success of above , I am calling below function to check whether all the required permissions have been granted by user or not ( in this case 'email' )

> facebookConnectPlugin.api('/me/permissions',["public_profile","email"], function(response) { 
//some code --lets say ABC
}

What is happening is that in case of mobile the second call (fb.api(me/permission) opens the permission dialog of facebook asking user to authorize for missing permissions. However in case of web, it just returns me the permissions and their status..

I am on the latest version of the plugin ( 0.10)

Another issue is that , if I deny the permissions on mobile again , and call the Login() api again for the permissions, it gives me the error in adb logcat
"Session: an attempt was made to request new permissions for a session that has a pending request"

**Comment by heroandtn3** [comment]
@aogilvie re-try `.login` does not work. It never shows permission dialog again, to re-ask permission, `auth_type` must be set to `rerequest`. Seethis [offical documentation](https://developers.facebook.com/docs/facebook-login/login-flow-for-web/v2.2#re-asking-declined-permissions).

**Comment by robotvert** [comment]
+1 for this.
Right now without being able to set the `auth_type: rerequest` parameter even if the user tries to login again it won't be shown the permissions screen.

**Comment by aogilvie** [comment]
On develop branch.
