### ISSUE TITLE
PhoneGap Build plugin version update?

### ISSUE THREAD

**Issue by jfaris** [Wizcorp/phonegap-facebook-plugin#839]
Is there an ETA for the latest version (0.10.1) to be available on PhoneGap Build?  What is the process for pushing updates to PGB?

Thanks!

**Comment by marmarko** [comment]
@aogilvie any updates?

**Comment by benmcmaster** [comment]
@nicholasareed @marmarko @aogilvie Would love to get the newest facebook plugin on Phonegap build. We desperately need it in the next version of our app. Does any of you have any new updates on this issue?

**Comment by aogilvie** [comment]
I've updated the README for PhoneGap Build. https://github.com/Wizcorp/phonegap-facebook-plugin/blob/develop/platforms/pg-build/README.md

**Comment by nicholasareed** [comment]
@aogilvie were you able to try out the technique I listed above? I wasn't able to get 0.10 or 0.11 to work correctly, but I did get an older version working (0.9.1): http://plugins.cordova.io/#/package/nickreed.com.phonegap.plugins.facebookconnect

I only needed it for authentication, so I have no idea if anything else works in it. This is also compatible with the Google+ plugin (http://plugins.cordova.io/#/package/nl.x-services.plugins.googleplus) so you can login with either in an app

**Comment by thauser777** [comment]
Where are we at on this?  Help!  I haven't seen any posts since January.

**Comment by benmcmaster** [comment]
We are nowhere on this: https://github.com/Wizcorp/phonegap-facebook-plugin/blob/develop/platforms/pg-build/README.md

You must use the 0.8.0 version of the plugin which has the ad identifier. For this reason and other plugin issues we are moving away from Phonegap Build. It's too slow, support isn't good. It's too risky.

**Comment by nicholasareed** [comment]
I built 0.11.0 a minute ago and posted a working (for me at least) version on plugins.cordova.io. Add it to your PGB app like: 

    <gap:plugin name="nickreed.com.phonegap.plugins.facebookconnect" version="0.11.0" source="plugins.cordova.io">
        <param name="APP_ID" value="999999999" />
        <param name="APP_NAME" value="App Name Here" />
    </gap:plugin>

To get it working I just ripped out (or renamed) the custom_rules.xml file that was causing an ant-build problem in Android, then replaced the symlinks in iOS with the actual files. 

After that, a simple `npm pack` (using my mods from the previous post) and uploaded the plugin using plugman.

**Comment by bau720123** [comment]
hi @nicholasareed 
I am a PGB's 3.7 user too
but if you really sure that these way can solve the problem
```
<gap:plugin name="nickreed.com.phonegap.plugins.facebookconnect" version="0.11.0" source="plugins.cordova.io">
    <param name="APP_ID" value="999999999" />
    <param name="APP_NAME" value="App Name Here" />
</gap:plugin>
```

I tried but still build fail in Android and iOS
do you want me to offer some log information for you

**Comment by bau720123** [comment]
hi @nicholasareed 
I notice another thing
if you install one of the plugin from "plugins.cordova.io"
Android will build fail too
http://plugins.cordova.io/#/package/nl.x-services.plugins.googleplus
http://plugins.cordova.io/#/package/de.appplant.cordova.plugin.local-notification

**Comment by nicholasareed** [comment]
paste a gist with the log (don't paste it into the comment stream). Most likely a conflict with another plugin
I've tried with a few apps and haven't had any trouble building. Trying a few more

**Comment by nicholasareed** [comment]
I'm not surprised there is a conflict with the googleplus plugin, that was what I originally set out to fix! Works fine on iOS, but android still has android-support jar conflicts with those plugins. I might have a chance to fix it later today or this week

**Comment by bau720123** [comment]
hi @nicholasareed 

when I only use "nickreed.com.phonegap.plugins.facebookconnect"
```
<gap:plugin name="nickreed.com.phonegap.plugins.facebookconnect" version="0.11.0" source="plugins.cordova.io">
 <param name="APP_ID" value="myid" />
 <param name="APP_NAME" value="myname" />
</gap:plugin>
```
Android will build success，but iOS will build fail (you can use your own explorer to see the log)
http://www.littlebau.com/ios_log.txt

when I use "nickreed.com.phonegap.plugins.facebookconnect" and ("nl.x-services.plugins.googleplus" or "de.appplant.cordova.plugin.local-notification")
```
<gap:plugin name="nickreed.com.phonegap.plugins.facebookconnect" version="0.11.0" source="plugins.cordova.io">
 <param name="APP_ID" value="myid" />
 <param name="APP_NAME" value="myname" />
</gap:plugin>
<gap:plugin name="nl.x-services.plugins.googleplus" version="1.1.0" source="plugins.cordova.io" />
or
<gap:plugin name="de.appplant.cordova.plugin.local-notification" version="0.8.1" source="plugins.cordova.io" />
```
iOS will also build fail but Android build fail too
http://www.littlebau.com/android_jpg.jpg
http://www.littlebau.com/android_log.txt

**Comment by nicholasareed** [comment]
I get the same unhelpful result for the android_log :( Cant really do any debugging with that. No idea if it is a conflict with paths, the android-support, etc.

**Comment by nicholasareed** [comment]
Actually, looks like the github issues are causing the current issue leading to that empty log. The error message (when you click the red button next to Log) has an error about being unable to reach the android-support-v4 repository on github.

**Comment by nicholasareed** [comment]
@bau720123 

The following works for me for both iOS and Android. Don't know about LocalNotifications, I don't use that plugin. 

    <gap:plugin name="nickreed.com.phonegap.plugins.facebookconnect" version="0.11.1" source="plugins.cordova.io">
        <param name="APP_ID" value="999999999" />
        <param name="APP_NAME" value="Your App Name Here" />
    </gap:plugin>
    <gap:plugin name="nl.x-services.plugins.googleplus" version="1.1.0" source="plugins.cordova.io"/>

**Comment by bau720123** [comment]
hi @nicholasareed 
seem still not work

I tried a lot of different way

way1，Android and iOS will all build fail
```
<gap:plugin name="com.phonegap.plugins.facebookconnect" version="0.11.0" source="plugins.cordova.io">
<param name="APP_ID" value="myid" />
<param name="APP_NAME" value="myname" />
</gap:plugin>
```

**Comment by bau720123** [comment]
hi @nicholasareed 
seem still not work (I only install facebook plugin and all latest core official plugin)

I tried a lot of different way

way 1，Android and iOS will all build fail
http://plugins.cordova.io/#/package/com.phonegap.plugins.facebookconnect
```
<gap:plugin name="com.phonegap.plugins.facebookconnect" version="0.11.0" source="plugins.cordova.io">
<param name="APP_ID" value="1111" />
<param name="APP_NAME" value="2222" />
</gap:plugin>
```

way 2，Android build success but iOS and winphone will build fail (I know there is no winphone version，but it will cause winphone Indirect build fail)
http://plugins.cordova.io/#/package/nickreed.com.phonegap.plugins.facebookconnect
```
<gap:plugin name="nickreed.com.phonegap.plugins.facebookconnect" version="0.11.1" source="plugins.cordova.io">
<param name="APP_ID" value="1111" />
<param name="APP_NAME" value="2222" />
</gap:plugin>
```

way 3，Android build success but iOS will build fail
http://plugins.cordova.io/#/package/jfaris.com.phonegap.plugins.facebookconnect
```
<gap:plugin name="jfaris.com.phonegap.plugins.facebookconnect" version="0.11.0-jfaris.0" source="plugins.cordova.io">
<param name="APP_ID" value="1111" />
<param name="APP_NAME" value="2222" />
</gap:plugin>
```

**Comment by nicholasareed** [comment]
I'm not sure why you're posting the other two version, I haven't tested them at all, just the one starting with "nickreed.com." 

Maybe you can post your entire config.xml file? I'm having no problem building for iOS and Android (WP will always break), been doing it all day with the plugin I worked on: 

    <gap:plugin name="nickreed.com.phonegap.plugins.facebookconnect" version="0.11.1" source="plugins.cordova.io">
        <param name="APP_ID" value="1111" />
        <param name="APP_NAME" value="2222" />
    </gap:plugin>

**Comment by bau720123** [comment]
hi @nicholasareed 
this is my full config.xml
you can download it and help me to see if there is any trouble...really thanks
http://www.littlebau.com/phonegap_build_3.7.1/config_j.xml

**Comment by nicholasareed** [comment]
Your setup worked fine for me: http://dl.dropbox.com/u/6673634/Screenshots/zuc4.png

Might be some other problem you're having.

**Comment by bau720123** [comment]
hi @nicholasareed 
ok...
maybe I will try more detail about this
if anything feedback，I will tell you
thanks

**Comment by bau720123** [comment]
hi @nicholasareed 
I tried many many times
iOS still build fail in PGB 3.7
just want to made a Confirm again
are you really use PGB 3.7 and build success ?
can you give me your app's page screenshot just like that I give you...
http://www.littlebau.com/0412.jpg

**Comment by nicholasareed** [comment]
I can't take a screenshot of my app, but I guarantee it is working fine for me. I tried the config.xml you sent me, and it worked without any problem (I did remove any non-english characters though). Take a screenshot of your plugin page (should look like http://dl.dropbox.com/u/6673634/Screenshots/zuc4.png) so I can see which ones PGB is seeing.

**Comment by nakomi** [comment]
Hi @nicholasareed is it possible to get the zip version of your plugin for ios since I am developing / building with cloud base IDE like Monaca.

Thanks a lot for your help:)

**Comment by nakomi** [comment]
I think I figure out fetch the plugin from plugins.cordova.io and zip by myself :).

It is successfully built but there is one issue in iOS it always pull up in-app browser not native facebook app even I have facebook app installed :| any thought?

**Comment by k-cgomezh** [comment]
Hi, we got the same issue with facebookconnect and local-notification.  We tried to use plugins from "plugins.cordova.io" but it fails too with the same error on dependency list. 

Is there any other way to use the local-notification plugin, like referencing the javascript code for the plugin and get it fixed  ?? 
 
<script src="local-notification.js"></script>

Best regards,

**Comment by bau720123** [comment]
hi @nicholasareed 
I finally know why you can build success
the point is "the upper case problem"
https://github.com/phonegap/build/issues/431

if your app's name start at upper case，it will build success
otherwise，it will build fail
https://github.com/Wizcorp/phonegap-facebook-plugin/issues/929
(see the like's button)

**Comment by bau720123** [comment]
hi @nicholasareed 
for now I am using PGB (build.phonegap.com) (cli-5.1.1 version with all latest core plugin from npm)
but it will appear the new error message (only in Android，iOS is build success)
```
release:

-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...
     [aapt] aapt: warning: string 'menu_settings' has no default translation in /project/com.google.playservices/phonegap-google-play-services_lib/res; found: ar bg ca cs da de el es eu fi fr he hi hu id it iw ja ko nl pl pt ru sk sl sv tr zh_CN zh_TW
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Compiling 111 source files to /project/bin/classes
    [javac] /project/src/com/phonegap/plugins/childBrowser/ChildBrowser.java:130: error: cannot find symbol
    [javac]                 intent = new Intent().setClass((Context) cordova.getActivity(), org.apache.cordova.DroidGap.class);
    [javac]                                                                                                   ^
    [javac]   symbol:   class DroidGap
    [javac]   location: package org.apache.cordova
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

BUILD FAILED
/home/ec2-user/android-sdk/tools/ant/build.xml:716: The following error occurred while executing this line:
/home/ec2-user/android-sdk/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.
```
