### ISSUE TITLE
Session: an attempt was made to request new permissions for a session that has a pending request

### ISSUE THREAD

**Issue by aniljailta** [Wizcorp/phonegap-facebook-plugin#855]
Hey guys,

I am trying to implement user like on a particular post.

I am working on a project where user can like and comment on a page feed post. platform i am using is

   cordova version : 3.5
   android : 4.4.4

 I am using ng-cordova with this plugin. Login is working fine but when i try to implement publish like then it throws an error "Session: an attempt was made to request new permissions for a session that has a pending request"

```
   //like fb post
     $scope.LIkePostFb =  function(post_id){
     $cordovaFacebook.getLoginStatus().then(function(success) {
              if(success.status !== 'connected'){
                $cordovaFacebook.login(["public_profile", "email", "user_friends"])
                      .then(function(success) {
                          var status = success.status;
                          if(status === 'connected'){
                             $cordovaFacebook.login(["publish_actions"]).then(function(response){
                                console.log(response); 
                             });
                             var response = success.authResponse;
                             storageService.save('LoggedInFb',response);
                          } 
                        });

                    }else{

                      $cordovaFacebook.api(post_id+"/likes", ["publish_actions"])
                            .then(function(success) {
                              // success
                              console.log(success)
                            }, function (error) {
                              // error
                              console.log(error);
                            });

                    }

               });
```

  }

This is how i am trying to get access token for publish. I have shown two method one is using login and other is using api

If user is not logged in , app ask for login and then prompt for publish action( because in android sdk we can't ask for both read and write together. but it never open that publish permission dialog).

Next method i am trying is using .api('post_id/likes',['publish_actions']) . it return me with error  Session: an attempt was made to request new permissions for a session that has a pending request

 How can i comment or post a like using android sdk and this plugin? Kindly help.

**Comment by MaicolBen** [comment]
For the organization api solution doesn't fix the problem, what is wrong with my code?  

    facebookConnectPlugin.login(["email"], function(response1) {
    		if (response1.status === 'connected') {
                       // reaches here
    			facebookConnectPlugin.api("me", ["user_birthday"], function(response) {
    				// never reached

    			}, function(response) {
    				// never reached
    			});
    		}

    	}, function(response) {
    		alert(JSON.stringify(response));
  	});

Because never reaches the second call.

Thanks

**Comment by rubens21** [comment]
I know this issue is quite old, but I was dealing with it today.
I found out a workaround to avoid the error "Session: an attempt was made to request...".

This error only happens when an api's call does not response, I do not know why it does not. However, in my case, it only happened when I was calling the .api method using a permission that the user does not have granted/declined yet.

So, I am calling the .login method again always when I need a new permission, and using the .api method after be sure that the user has granted me the permission.

I hope it may be useful for someone else.
