### ISSUE TITLE
Android problem with 'require'

### ISSUE THREAD

**Issue by tgriffo** [Wizcorp/phonegap-facebook-plugin#869]
Hi folks,

possibly a very basic issue, but ran out of ideas to try by myself.

When deploying the app to an Android device I get the below error.

D/CordovaLog(11331): file:///android_asset/www/lib/facebookConnectPlugin.js: Line 181 : Uncaught ReferenceError: **require is not defined**
E/Web Console(11331): **Uncaught ReferenceError: require is not defined:181**
D/dalvikvm( 2554): GC_CONCURRENT freed 1771K, 38% free 14964K/23920K, paused 3ms+3ms, total 38ms
D/CordovaLog(11331): file:///android_asset/www/lib/ionic/js/ionic.bundle.js: Line 17696 : **TypeError: Cannot call method 'getLoginStatus' of undefined**

I tried including RequireJS as part of my app, however if I do that I get the following error:

**Module name "cordova/exec" has not been loaded yet for context**

on the line: 
```javascript
var exec = require("cordova/exec");
```

Any ideas?

**Comment by tgriffo** [comment]
Sorted folks - as I mentioned in the beginning it was a basic issue. I was using the API before deviceready hence all the problems were happening - all sorted now. Apologies for the wasted issue #.

**Comment by jamesdef** [comment]
where exactly did you put this? I'm experiencing the same now

**Comment by aogilvie** [comment]
@jamesdef all Cordova or Cordova plugin APIs can only be used once this code has fired:

`document.addEventListener('deviceready', function () { console.log("device is ready") }, false)`;

**Comment by dittops** [comment]
I understand i need to add my code inside deviceready.  Maybe i'm not understanding well. The plugin is added in the index.html. So the require being called before that. How can i solve that? Please help me on this

**Comment by renanbastos93** [comment]
I have problem equals of you, please help.
