### ISSUE TITLE
Empty result for '/me/friends?limit=2000

### ISSUE THREAD

**Issue by BalticDistribution** [Wizcorp/phonegap-facebook-plugin#870]
While running the below code on IOS I get the list of my friends, while on Android get an empty result:

facebookConnectPlugin.login( ["email"], -> this runs fine
                function (response) {                            
                         facebookConnectPlugin.api(
                                 '/me/friends?limit=2000',
                                 null,
                                 function(response) {
                                    response.data.length -> iphone OK, Android empty 
                                 },
                               function(response) { }
                             );
                            },
            function (response) {   }
);

**Comment by plantastika** [comment]
The same thing here, iOS work fine but android is empty, any help??

**Comment by aogilvie** [comment]
I'm not sure, in both cases iOS and Android return the result object directly from Facebook without adding or removing anything. This is highly likely a Facebook SDK bug.

Success return for Android:
https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java#L640

Success return for iOS:
https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/platforms/ios/HelloCordova/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m#L548

I recommend filing a bug here: https://developers.facebook.com/bugs

**Comment by BalticDistribution** [comment]
No offence aogilivie but I don't consider it closed.
Regards

**Comment by plantastika** [comment]
I agree with baltic

**Comment by plantastika** [comment]
hi baltic, I finally make it work in android, the solution is very simple, just do not ask permission again, change:

facebookConnectPlugin.api('/me/friends?limit=2000',null,

for this

facebookConnectPlugin.api('/me/friends?limit=2000',[],

**Comment by aogilvie** [comment]
@BalticDistribution None taken :)
Majority of issues here are opened and never followed up by the OP. Closing if not proven to be an issue with the plugin code itself and other such reasons seems valid to me. Issues can be re-opened anytime and for that reason I think closing an issue sometimes early is not a big deal.

This also helps me (the sole maintainer :/) to keep track "real" issues (when their is either an immediate bug or follow up from a user either for debugging or feature request).

I'm glad you found a solution to the problem :) I had another dip (double dip? xD) into the code and there is no scenario that stands out where the permissions object can effect the results from a Graph API call.
