### ISSUE TITLE
iOS: Race condition with graphAPI

### ISSUE THREAD

**Issue by ggmichaelgo** [Wizcorp/phonegap-facebook-plugin#873]
There is a race condition with facebookConnectPlugin
Here is the code to replicate it

    facebookConnectPlugin.api('/me', null, function(response){
      console.log('me');
      console.log(response);
    });
    setTimeout(function(){
      facebookConnectPlugin.api('/me/permissions', null, function(response){
        console.log('permission');
        console.log(response);
      });
    }, 70)

In the console, only the "/me/permissions" request will get returned with the "/me" request's response data.

This is happening because on the 2nd call, the FacebookConnectPlugin.m sets the graphCallbackId value to 2nd call's callbackId.
So, the 1st call will get the response from the Facebook API first, and then callback to 2nd request.

**Comment by aogilvie** [comment]
Thanks.
