### ISSUE TITLE
working with vs2013 cordova plugin

### ISSUE THREAD

**Issue by cavevs** [Wizcorp/phonegap-facebook-plugin#876]
Hi guys,
I've installed Visual Studio Tools for Apache Cordova CTP3.
Is there any guide showing how to make it working?.

Thanks

**Comment by duftstenen** [comment]
Hi cavevs - did you manage to get this to work for Visual Studio Tools for Apache Cordova CTP3?

Best,

**Comment by cavevs** [comment]
hi, no.I really dont know how to make it working.Any suggest?
Thanks
Il 08/gen/2015 11:07 "duftstenen" <notifications@github.com> ha scritto:

**Comment by aogilvie** [comment]
@cavevs There is no guide and it is not currently supported. You can try ping Microsoft dev team on Twitter: https://twitter.com/msdev
