### ISSUE TITLE
Login Status Events

### ISSUE THREAD

**Issue by djabif** [Wizcorp/phonegap-facebook-plugin#878]
Hi, thanks for the plugin it's great!
I need to suscribe to login status events like it explains here: https://developers.facebook.com/docs/reference/javascript/FB.getLoginStatus

For example:
```
FB.Event.subscribe('auth.login', function(response) {
});
```
This works great in the browser because it uses javascript SDK, but does not work on iOS because this feature is not implemented yet in the plugin. I would really appreciate if you can add this feature to the plugin.

Thanks!

**Comment by agustinhaller** [comment]
+1

**Comment by djabif** [comment]
hello????

**Comment by aogilvie** [comment]
@djabif The plugin API is not eventy. You can however get the status of login with:
`facebookConnectPlugin.getLoginStatus(Function success, Function failure)`
Check the readme for example return object.
