### ISSUE TITLE
the pligin will build error by PGB

### ISSUE THREAD

**Issue by bau720123** [Wizcorp/phonegap-facebook-plugin#879]
all detail right here
http://community.phonegap.com/nitobi/topics/-com-phonegap-plugins-facebookconnect-will-build-faile-in-android

**Comment by aogilvie** [comment]
We no longer support PhoneGap Build since they changed their policy (added fee for uploading a plugin) https://github.com/Wizcorp/phonegap-facebook-plugin/issues/839#issuecomment-67608814 Sorry.

**Comment by bau720123** [comment]
well...so sad
anyway...thanks

**Comment by bau720123** [comment]
hi
although I use PGB 3.6.3
but now I install your plugin from plugins.cordova.io and use version 0.10.1
this is PGB's log information
http://www.littlebau.com/20141211/log2.html

**Comment by aogilvie** [comment]
You need to remove this folder: `/project/com.phonegap.plugins.facebookconnect/FacebookLib/bin/res/crunch`

**Comment by bau720123** [comment]
hi @apogilive
but in PGB (build.phonegap.com)...
how could do this ?

**Comment by aogilvie** [comment]
No idea :/

**Comment by MaicolBen** [comment]
@bau720123 do you have any news? Seems that I have to move the build to local.

**Comment by bau720123** [comment]
hi @MaicolBen 
I have no idea for this plugin with PGB (build.phonegap.com)
I am studying Cordova cli 5.0 recently

in cli 5.0
I use this plugin to instead (maybe you can try this in PGB)
com.phonegap.plugins.okaybmd.facebookconnect
but... I am not really try if it's work in true device

**Comment by MaicolBen** [comment]
@bau720123 Thanks! But don't works with it, maybe the api changed a lot with this repo.

Maybe someone has to update this doc https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/platforms/pg-build/README.md
