### ISSUE TITLE
Facebook Graph API 2.0 / 2.1 supported?

### ISSUE THREAD

**Issue by ozantopoglu** [Wizcorp/phonegap-facebook-plugin#884]
As explained in the link below Facebook will depreciate Graph API 1.0 which will impact the login process as of April 2015.
https://developers.facebook.com/docs/apps/upgrading/
Does facebook plugin support the new Facebook Graph API 2.0 / 2.1? If so from which version onwards?

**Comment by aogilvie** [comment]
Yes. 2.0+ supported. All versions upwards.
