### ISSUE TITLE
Activity Result in plugin:Request Code(64206) error code(-1).not able to redirect to a different page after login

### ISSUE THREAD

**Issue by apurva2491** [Wizcorp/phonegap-facebook-plugin#885]
I tried almost both solution which ever is present in previous issues but that is not working for me. what happening is the account which is associated with facebook developer with that every thing is working properly but with another account after getting all the details I am not able to redirect user to a different page it shows the above error.please help me with this.

**Comment by aogilvie** [comment]
Please read the Issue Guidelines before creating an issue. You are missing the following information:
- sample code to re-produce the error
- clear platform spec information (error looks like Android but a page redirect sounds like JavaScript SDK)
- full console log when possible
