### ISSUE TITLE
Android Feed href

### ISSUE THREAD

**Issue by joaopedroft** [Wizcorp/phonegap-facebook-plugin#886]
Hi, my href attribute is not working on Android feed.
Is just me or anyone have the same issue?

**Comment by joaopedroft** [comment]
I found out that i need to use link attribute insted href.

**Comment by aogilvie** [comment]
@joaopedroft Thanks for creating the issue. We fixing with this https://github.com/Wizcorp/phonegap-facebook-plugin/pull/896 on develop branch. both `link` and `href` will be supported. Thanks.
