### ISSUE TITLE
how to retrieve all friends list?

### ISSUE THREAD

**Issue by raviteja-adusumalli** [Wizcorp/phonegap-facebook-plugin#891]
Hi,
I am tring to fetch friend list. facing issue with fetching all friends.
facebookConnectPlugin.api("me/friends", ['user_friends'], function_success, function_error) is only retriving friends who have authorised the app. 
how to retrive all friends list

note: 
i have google about the issue and got some answers like after graph api version 2+  'me/friends' will only fetch friends who have authroized the app.

http://stackoverflow.com/questions/23417356/facebook-graph-api-v2-0-me-friends-returns-empty-or-only-friends-who-also-u

I am having some apps in my mobile which can fetch all my fb friends list. is there any way to fetch all  friends list

Thanks

**Comment by aogilvie** [comment]
The answer provided on stackoverflow is 100% accurate i'm afraid, sorry.
