### ISSUE TITLE
Oh geez.... with facebookConnect 

### ISSUE THREAD

**Issue by kfir-d** [Wizcorp/phonegap-facebook-plugin#893]
Hey,
I work with PhoneGap build the latest version and have a problem to build a version of IOS I get an error:
Oh geez. Your build failed. Sorry, but a problem occurred on the build server

This log:

1 warning generated.

CompileC build/myApp.build/Release-iphoneos/myApp.build/Objects-normal/armv7/FacebookConnectPlugin.o myApp/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DCORDOVA_FRAMEWORK=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=6.0 -iquote /project/build/myApp.build/Release-iphoneos/myApp.build/myApp-generated-files.hmap -I/project/build/myApp.build/Release-iphoneos/myApp.build/myApp-own-target-headers.hmap -I/project/build/myApp.build/Release-iphoneos/myApp.build/myApp-all-target-headers.hmap -iquote /project/build/myApp.build/Release-iphoneos/myApp.build/myApp-project-headers.hmap -I/project/build/include -I/project/build/usr/local/lib/include -I/project/build/UninstalledProducts/include -I/project/build -I/project/build/myApp.build/Release-iphoneos/myApp.build/DerivedSources/armv7 -I/project/build/myApp.build/Release-iphoneos/myApp.build/DerivedSources -F/project/build -Fcordova/plugins/com.phonegap.plugins.facebookconnect/platforms/android/res/xml/Plugins/com.phonegap.plugins.facebookconnect -include /var/folders/b2/s6cv_gm10h53_s9lhg72_1cw0000gp/C/com.apple.DeveloperTools/6.1-6A1052d/Xcode/SharedPrecompiledHeaders/myApp-Prefix-hagixozqxzgqlbhckgbynrcsqgyi/myApp-Prefix.pch -MMD -MT dependencies -MF /project/build/myApp.build/Release-iphoneos/myApp.build/Objects-normal/armv7/FacebookConnectPlugin.d --serialize-diagnostics /project/build/myApp.build/Release-iphoneos/myApp.build/Objects-normal/armv7/FacebookConnectPlugin.dia -c /project/myApp/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m -o /project/build/myApp.build/Release-iphoneos/myApp.build/Objects-normal/armv7/FacebookConnectPlugin.o
clang: error: no such file or directory: '/project/myApp/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

** BUILD FAILED **

The following build commands failed:
	CompileC build/myApp.build/Release-iphoneos/myApp.build/Objects-normal/armv7/FacebookConnectPlugin.o myApp/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by plantastika** [comment]
That seems to be a compiler error, is weird if you did with phonegap build since everything is updated, I would try to prove in another browser....

**Comment by aogilvie** [comment]
@kfir-d I'm afraid we have stopped supporting PhoneGap Build since PhoneGap Build started charging developers to submit plugins to PhoneGap Build. Sorry.

https://github.com/Wizcorp/phonegap-facebook-plugin/blob/develop/platforms/pg-build/README.md
