### ISSUE TITLE
facebookConnectPlugin is not defined (using ngCordova & Ionic)

### ISSUE THREAD

**Issue by colinory** [Wizcorp/phonegap-facebook-plugin#894]
Trying to get it work. 

This is my code:

```javascript
angular.module('starter.controllers', ['ngCordova'])

.config(function($cordovaFacebookProvider) {
    var appID = 123456789;
    var version = "v2.0"; // or leave blank and default is v2.0
    $cordovaFacebookProvider.browserInit(appID, version);
})
```

Which leads to this error >
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module starter due to:
Error: [$injector:modulerr] Failed to instantiate module starter.controllers due to:
ReferenceError: facebookConnectPlugin is not defined
    at browserInit (http://localhost:8100/lib/ngCordova/dist/ng-cordova.js:1576:7)
    at http://localhost:8100/js/controllers.js:6:30
    at Object.invoke (http://localhost:8100/lib/ionic/js/ionic.bundle.js:11994:17)
    at runInvokeQueue (http://localhost:8100/lib/ionic/js/ionic.bundle.js:11900:35)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:11909:11
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:8147:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:11890:5)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:11907:40
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:8147:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:11890:5)
```

Tried a couple of things but without any positive result:
- When I build it and run it on my device the app displays a blank screen

- Tried the normal cordova js code:

- Changed $cordovaFacebookProvider to $cordovaFacebook (based on this thread: 
http://forum.ionicframework.com/t/unknown-provider-cordovaprovider/13305/3

- And this is a another related thread, but doesn't help me thought..
http://forum.ionicframework.com/t/does-ng-crodova-has-facebook-login/9163

I already have a prototype working with the fb auth in the in-app-browser. But I really want to have a native fb connect functionality.

**Comment by aogilvie** [comment]
@colinory Hi thanks for the beautifully written issue (I don't get may of these :( ...), sadly, you want to write this issue on https://github.com/driftyco/ng-cordova. This guy / team do stuff to put this plugin into Ionic directive.

**Comment by lrettig** [comment]
For someone else who lands here from Google, this is likely related to https://github.com/Wizcorp/phonegap-facebook-plugin/issues/866 and due to https://github.com/driftyco/ionic-cli/issues/354 which hasn't been solved.
