### ISSUE TITLE
After installing the facebook plugin i get a compile error

### ISSUE THREAD

**Issue by do-web** [Wizcorp/phonegap-facebook-plugin#897]
I get this error when i use the fb plugin with Crosswalk installed:

  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)

**Comment by aogilvie** [comment]
@do-web 
You probably have multiple android.support.v4.jar files in your project. There can only be one at compile time.
If they are different versions of the android support lib then you could be in quite some trouble if different classes require specific versions of android support lib.
If deleting one is not enough you can try some of these SO answers: http://stackoverflow.com/questions/20989317/multiple-dex-files-define-landroid-support-v4-accessibilityservice-accessibility
