### ISSUE TITLE
Thread Warnings ? Not possible to Background ?

### ISSUE THREAD

**Issue by alxpereira** [Wizcorp/phonegap-facebook-plugin#900]
Hi guys,
I'm just curious, as we all have some THREAD Warning on the Cordova IOS Plugin, is it possible to update the plugin as it could use only Background Threads ?

Thanks

**Comment by aogilvie** [comment]
@alxpereira Duplicate https://github.com/Wizcorp/phonegap-facebook-plugin/issues/488
