### ISSUE TITLE
Cordova invite friend to app

### ISSUE THREAD

**Issue by kiempoturner** [Wizcorp/phonegap-facebook-plugin#903]
Hi, 

I need to invite friends to use my app, whats the API call?

I read here (https://developers.facebook.com/docs/games/invitable-friends/v2.2) that it is only accessible for Games app. Any workaround or solution for this ?

Thanks.

**Comment by kiempoturner** [comment]
Is this an irrelevant question?

**Comment by kiempoturner** [comment]
im closing this, got the solution.


,,,,
facebookConnectPlugin.showDialog(
			{
			    method: "apprequests",
			    message: "check this out!."
			},
		    function success,
		    function (error) {console.log("ini error showdialog ni: " + error) }
		);
,,,,

**Comment by avishayhajbi** [comment]
that was your solution?
thanks

**Comment by promactkaran** [comment]
not a working solution if your app is a normal app, it works only if the app is categorised as "Game".
