### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by nasht00** [Wizcorp/phonegap-facebook-plugin#911]
Before I start using this, some questions:

- The last commit is from more than 1 year ago. Is the project still alive?
- Is it still working?
- It claims to be "the official plugin for Facebook in Apache Cordova" - official in what sense?

No offense, I just want to make sure it's a safe bet to choose facebook as a login.

**Comment by kaansoral** [comment]
It's been stable for some time now: https://github.com/Wizcorp/phonegap-facebook-plugin

Also the last commit seems to be a month ago

You can go ahead and use it, the only issues are edge authentication cases, which will likely not occur on production environments, those issues might also be eminating from the Facebook SDK/logic itself
