### ISSUE TITLE
Init Events

### ISSUE THREAD

**Issue by strazi** [Wizcorp/phonegap-facebook-plugin#912]
I have a version of my app on the store in iOS where I manually added the Facebook SDK to XCode and in the app events on Facebook I get things like: App Launches, App Installs, Completed Sessions.

I am using this plugin for the Android version, but it doesn't seem to send the same events automatically? I am able to manually send events via the console, so I know it's connected to Facebook correctly, I'm just wondering if those default events on iOS are a part of this plugin?

**Comment by aogilvie** [comment]
@strazi Yes all session based events are automatically tracked for you in this plugin. For Android you may have the same issue as: https://github.com/Wizcorp/phonegap-facebook-plugin/issues/877
