### ISSUE TITLE
Unfortunately app has stopped 

### ISSUE THREAD

**Issue by pratikm23** [Wizcorp/phonegap-facebook-plugin#913]
I am getting this error after using the facebook plugin and whenever i sign the apk from eclipse . 
The application is not opening at all. After i remove the plugin the application works fine. 
Please let me know how to solve this issue.

**Comment by kaansoral** [comment]
Is it random or does the application stop almost immediately?

I also have been getting random stops with no reason or logs, that's why I'm asking

**Comment by pratikm23** [comment]
The App immediately stops and does not open at all .

**Comment by kaansoral** [comment]
I've never heard of this specific issue, so I won't be able to help you, but you might get better help if you post the logs of the device, it might show why the app is instantly dying

**Comment by aogilvie** [comment]
Closed. Does not adhere to the [contribution guidelines](https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/CONTRIBUTING.md)
