### ISSUE TITLE
Version 0.11.0 on cordova repository

### ISSUE THREAD

**Issue by bluepioupiou** [Wizcorp/phonegap-facebook-plugin#917]
Hi all. I'm using the plugin on my app and I really need the feature to send a private message (issue #593). Apparently this is ready in version 0.11.0, wich is tagged and release, but in cordova registry I can only find 0.10.1. Is it your 'team' that upload the versions on cordova registry ? if yes do you think it can be done soon ? if no, who should I write to ?

Thanks in advance

**Comment by andres99x** [comment]
@bluepioupiou you can wait till the version gets uploaded, or you can download the repo, and add it to your projects.

```phonegap plugin add /local/path/to/plugin/```

I hope that helps. good luck

**Comment by bluepioupiou** [comment]
You mean "cordova plugin add ...." ?

In fact, I've already done that to test this new functionnality. I event used directly the github project with the good cset.
But now I want to deliver it with phonegap build. And for that I think I need it to be availaible eitheir on cordova registry or on phonegap registry....

**Comment by bluepioupiou** [comment]
Hi again, does someone can do something about that ?

**Comment by aogilvie** [comment]
@bluepioupiou 
@andres99x 
*boom!* done.
http://plugins.cordova.io/#/package/com.phonegap.plugins.facebookconnect

**Comment by bluepioupiou** [comment]
yes, thanks
