### ISSUE TITLE
Android Login Dialog Cancel Event

### ISSUE THREAD

**Issue by andres99x** [Wizcorp/phonegap-facebook-plugin#919]
Is there some way to know if the user canceled or closed (with the [X]) the login dialog?

Because when the user clicks the signin button i display a spinner, but i have no way to know when to remove it if the user cancels the dialog. 

Thanks!

**This is the dialog im talking about:**

![screen shot 2015-02-04 at 3 17 04 pm](https://cloud.githubusercontent.com/assets/5315776/6045595/9bc33326-ac82-11e4-960a-dee5d4a07b97.png)
![screen shot 2015-02-04 at 3 18 32 pm](https://cloud.githubusercontent.com/assets/5315776/6045578/6f5415a8-ac82-11e4-90aa-808fa96f949b.png)

**Comment by aogilvie** [comment]
Yes in the error callback to facebookConnect.login() you should receive this;

```
{
    "errorMessage": "User cancelled dialog",
    "errorCode": "4201"
}
```

tested; branch develop, sample project
device; Samsung Galaxy S3, Android 4.3
![photo on 2-5-15 at 6 54 pm](https://cloud.githubusercontent.com/assets/970364/6058240/d8771e68-ad68-11e4-8707-c5c6ffd18ca3.jpg)

**Comment by andres99x** [comment]
@aogilvie I was using v0.10.1, now im using the branch: develop and works fin.

Thank you very much!
