### ISSUE TITLE
Can't add platform android

### ISSUE THREAD

**Issue by braianj** [Wizcorp/phonegap-facebook-plugin#921]
When adding platform android ir return this error:

Failed to install 'com.phonegap.plugins.facebookconnect':Error: Variable(s) missing: APP_ID, APP_NAME

and after that error, if i install again and do cordova build android return this

BUILD FAILED
/Android SDK/adt-bundle-mac-x86_64-20140702/sdk/tools/ant/build.xml:720: The following error occurred while executing this line:
/Android SDK/adt-bundle-mac-x86_64-20140702/sdk/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

Total time: 7 seconds

/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: debug,-f, /platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
ERROR building one of the platforms: Error: /platforms/android/cordova/build: Command failed with exit code 8
You may not have the required environment or OS to build this project

But it works on android. Can you help me?

**Comment by garfik11** [comment]
same shit

**Comment by braianj** [comment]
reinstall the plugin and it works, but just the facebook plugin.
the ant error still there

**Comment by alamops** [comment]
About the Ant Error: you need to install it. You can install ant with ruby and brew, just google it.

**Comment by braianj** [comment]
the ant was installed, problem was another, but i have a new problem that I'll put a new issue. 
This issue is closed
