### ISSUE TITLE
Message Dialog support

### ISSUE THREAD

**Issue by dankingston** [Wizcorp/phonegap-facebook-plugin#923]
Is there any planned support for Message Dialog?
[Message Dialog for iOS](https://developers.facebook.com/docs/ios/share#message-dialog)
[Message Dialog for Android](https://developers.facebook.com/docs/android/message-dialog/)

**Comment by ronkorving** [comment]
This is first and foremost a community driven plugin. The best way to see features land is to contribute them.

**Comment by dankingston** [comment]
Just had a look into the code and realised Message Dialog is already there!

The latest version of this plugin on the [phonegap website](https://build.phonegap.com/plugins/1246) is 0.9.0. Is it possible to update to version 0.11.0?

**Comment by aogilvie** [comment]
Hi, the latest version on Cordova registry is 0.10.1, we will publish a new release shortly.

We have decided not to offer support for PhoneGap Build - https://github.com/Wizcorp/phonegap-facebook-plugin/issues/839#issuecomment-67608814

However, if you require a feature that is on the develop branch you can install locally by cloning the repository to ad installing it with PhoneGap CLI and a local file path to the folder on your machine.
