### ISSUE TITLE
Android - Error when building inside eclipse

### ISSUE THREAD

**Issue by braianj** [Wizcorp/phonegap-facebook-plugin#924]
After while trying to install this plugin, and working fine in iOS, when I make the build inside android, it said:

WebDialog cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 436    Java Problem
WebDialog cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 436    Java Problem
FacebookDialog cannot be resolved to a type ConnectPlugin.java  /src/org/apache/cordova/facebook   line 447    Java Problem
Session cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 436    Java Problem
UiLifecycleHelper cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 454    Java Problem
FacebookDialog cannot be resolved to a type ConnectPlugin.java  /src/org/apache/cordova/facebook   line 447    Java Problem
WebDialog cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 463    Java Problem
WebDialog cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 463    Java Problem
FacebookDialog cannot be resolved to a type ConnectPlugin.java  /src/org/apache/cordova/facebook   line 472    Java Problem
Session cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 463    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 561    Java Problem
FacebookDialog cannot be resolved to a type ConnectPlugin.java  /src/org/apache/cordova/facebook   line 472    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 622    Java Problem
FacebookOperationCanceledException cannot be resolved to a type ConnectPlugin.java  /src/org/apache/cordova/facebook   line 573    Java Problem
Response cannot be resolved to a type   ConnectPlugin.java  /src/org/apache/cordova/facebook   line 634    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 629    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 290    Java Problem
Session cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 290    Java Problem
AppEventsLogger cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 310    Java Problem
AppEventsLogger cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 337    Java Problem
AppEventsLogger cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 341    Java Problem
AppEventsLogger cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 357    Java Problem
FacebookDialog cannot be resolved   ConnectPlugin.java  /src/org/apache/cordova/facebook   line 395    Java Problem
FacebookDialog cannot be resolved to a variable ConnectPlugin.java  /src/org/apache/cordova/facebook   line 395    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 399    Java Problem
Session cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 399    Java Problem
OnCompleteListener cannot be resolved to a type ConnectPlugin.java  /src/org/apache/cordova/facebook   line 413    Java Problem
OnCompleteListener cannot be resolved to a type ConnectPlugin.java  /src/org/apache/cordova/facebook   line 413    Java Problem
FacebookException cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 416    Java Problem
WebDialog cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 428    Java Problem
WebDialog cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 428    Java Problem
Session cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 428    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 235    Java Problem
Session cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 233    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 229    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 213    Java Problem
SessionState cannot be resolved to a type   ConnectPlugin.java  /src/org/apache/cordova/facebook   line 241    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 241    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 239    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 235    Java Problem
Session cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 267    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 267    Java Problem
Session cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 252    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 252    Java Problem
Response cannot be resolved to a type   ConnectPlugin.java  /src/org/apache/cordova/facebook   line 274    Java Problem
GraphUser cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 274    Java Problem
GraphUserCallback cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 272    Java Problem
Session cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 268    Java Problem
UiLifecycleHelper cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 115    Java Problem
AppEventsLogger cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 117    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 97 Java Problem
SessionState cannot be resolved to a type   ConnectPlugin.java  /src/org/apache/cordova/facebook   line 97 Java Problem
UiLifecycleHelper cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 131    Java Problem
UiLifecycleHelper cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 139    Java Problem
UiLifecycleHelper cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 121    Java Problem
UiLifecycleHelper cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 125    Java Problem
FacebookDialog cannot be resolved to a type ConnectPlugin.java  /src/org/apache/cordova/facebook   line 147    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 153    Java Problem
FacebookDialog cannot be resolved to a type ConnectPlugin.java  /src/org/apache/cordova/facebook   line 139    Java Problem
FacebookDialog cannot be resolved to a type ConnectPlugin.java  /src/org/apache/cordova/facebook   line 141    Java Problem
Session cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 178    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 213    Java Problem
Session cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 153    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 178    Java Problem
FacebookServiceException cannot be resolved to a type   ConnectPlugin.java  /src/org/apache/cordova/facebook   line 797    Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 737    Java Problem
FacebookRequestError cannot be resolved to a type   ConnectPlugin.java  /src/org/apache/cordova/facebook   line 766    Java Problem
SessionState cannot be resolved to a type   ConnectPlugin.java  /src/org/apache/cordova/facebook   line 681    Java Problem
GraphUser cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 696    Java Problem
Session cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 91 Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 93 Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 93 Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 95 Java Problem
AppEventsLogger cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 80 Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 89 Java Problem
Session cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 89 Java Problem
SessionState cannot be resolved to a variable   ConnectPlugin.java  /src/org/apache/cordova/facebook   line 90 Java Problem
UiLifecycleHelper cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 71 Java Problem
UiLifecycleHelper cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 77 Java Problem
UiLifecycleHelper cannot be resolved to a type  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 77 Java Problem
AppEventsLogger cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 80 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 43 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 44 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 45 Java Problem
AppEventsLogger cannot be resolved to a type    ConnectPlugin.java  /src/org/apache/cordova/facebook   line 62 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 40 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 39 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 42 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 41 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 36 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 35 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 38 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 37 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 32 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 31 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 34 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 33 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 28 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 30 Java Problem
The import com.facebook cannot be resolved  ConnectPlugin.java  /src/org/apache/cordova/facebook   line 29 Java Problem

Can anyone help me?

**Comment by aogilvie** [comment]
As you can see at the end of your errors are multiple `The import com.facebook cannot be resolved ..`. This means your project is not being linked against the Facebook SDK for some reason. This libarary project must be added as linked to.

Add the library as a project dependency project -> properties -> javabuildpath -> project.

**Comment by braianj** [comment]
Sorry aogilvie but that don't solve the problem, so i don't see why you close it.
To solve the build problem it's necessary to  properties/android and remove the facebook library. Then build and the add the facebook library again. So for me this still es an issue, and shouldn't be closed.
Hope you correct that.
Regards

**Comment by marlon1088** [comment]
i have the same problem, are you solve that?

**Comment by braianj** [comment]
Finally this works for me 
Add the library as a project dependency project -> properties -> javabuildpath -> project. Button Add then find your facebook library and check it.
BUT you need to delete the from project -> properties -> android the library if it's added there.

**Comment by infinito84** [comment]
My solution:

facebooklib.jar is recompiled but FacebookLib does'nt have src, then facebooklib.jar is empty but exists, so, you have to copy again facebooklib.jar to FacebookLib/bin/ and doesn't recompiling. And restart eclipse :)
