### ISSUE TITLE
Could not find com.parse.bolts:bolts-android:1.1.2.

### ISSUE THREAD

**Issue by fernandopg** [Wizcorp/phonegap-facebook-plugin#926]
Hi!

After install phonegap-facebook-plugin in my app I get this error when I build:

    * What went wrong:
    A problem occurred configuring root project 'android'.
    > Could not resolve all dependencies for configuration ':_debugCompile'.
       > Could not find com.parse.bolts:bolts-android:1.1.2.
         Searched in the following locations:
             file:/Users/fernandopascuagarcia/Library/Android/sdk/extras/android/m2repository/com/parse/bolts/bolts-android/1.1.2/bolts-android-1.1.2.pom
             file:/Users/myuser/Library/Android/sdk/extras/android/m2repository/com/parse/bolts/bolts-android/1.1.2/bolts-android-1.1.2.jar
             file:/Users/myuser/Library/Android/sdk/extras/google/m2repository/com/parse/bolts/bolts-android/1.1.2/bolts-android-1.1.2.pom
             file:/Users/myuser/Library/Android/sdk/extras/google/m2repository/com/parse/bolts/bolts-android/1.1.2/bolts-android-1.1.2.jar
     Required by:
         :android:unspecified > com.facebook.android:staging-FacebookLib:3.21.1

To install the plugin I did the following:

     // clone the repo
     git clone https://github.com/Wizcorp/phonegap-facebook-plugin.git phonegap-facebook-plugin/
     // install it in my project
    cordova -d plugin add /Users/myuser/projects/phonegap-facebook-plugin --variable APP_ID="xxxxxxxxx" --variable APP_NAME="yyyyyyy"

After doing it I rebuild my project and I get this error:

    Error:(13, 0) Could not find property 'ANDROID_BUILD_MIN_SDK_VERSION' ...

That I solved doing the changes that recommend here in com.phonegap.plugins.facebookconnect/build.gradle (http://stackoverflow.com/questions/24466921/android-studio-0-8-1-how-to-use-facebook-sdk):

        compileSdkVersion 21
        buildToolsVersion '21.1.1'

        defaultConfig {
            minSdkVersion 14
            targetSdkVersion 21
        }

But after doing that I get the error that I said at first:

    * What went wrong:
    A problem occurred configuring root project 'android'.
    > Could not resolve all dependencies for configuration ':_debugCompile'.
       > Could not find com.parse.bolts:bolts-android:1.1.2.
         Searched in the following locations:
             file:/Users/fernandopascuagarcia/Library/Android/sdk/extras/android/m2repository/com/parse/bolts/bolts-android/1.1.2/bolts-android-1.1.2.pom
             file:/Users/myuser/Library/Android/sdk/extras/android/m2repository/com/parse/bolts/bolts-android/1.1.2/bolts-android-1.1.2.jar
             file:/Users/myuser/Library/Android/sdk/extras/google/m2repository/com/parse/bolts/bolts-android/1.1.2/bolts-android-1.1.2.pom
             file:/Users/myuser/Library/Android/sdk/extras/google/m2repository/com/parse/bolts/bolts-android/1.1.2/bolts-android-1.1.2.jar
     Required by:
         :android:unspecified > com.facebook.android:staging-FacebookLib:3.21.1

Please help me! I don't know what I'm doing wrong... I searched a lot in Google about this bug without success...

Thanks in advance!

**Comment by aogilvie** [comment]
@fernandopg It looks like something went wrong with your CLI install :/
Please check for this file `bolts-android-1.1.2.jar` https://github.com/Wizcorp/phonegap-facebook-plugin/tree/master/platforms/android/FacebookLib/libs
If you cannot find it in your `/libs` folder try download it again. If it is there make sure it is linked to your project.

**Comment by fernandopg** [comment]
Hi @aogilvie !

The file is in staging-FacebookLib/libs/bolts-android-1.1.2.jar, it is ok?

How can I link this library to my project? I'm using Android Studio 1.0.2

Open module Setting -> Dependencies seems be empty... 

![captura de pantalla 2015-02-17 a las 13 59 03](https://cloud.githubusercontent.com/assets/823395/6228724/b9e3b7ea-b6af-11e4-9312-0c33014693a9.png)

I'm new with Android Development... thanks!
