### ISSUE TITLE
Upload image to a new album

### ISSUE THREAD

**Issue by sunojvijayan** [Wizcorp/phonegap-facebook-plugin#927]
Is it possible to create a new album and upload a photo in it?

**Comment by aogilvie** [comment]
Technically this should be possible with the Graph API see : https://developers.facebook.com/docs/graph-api/reference/v2.2/album?locale=ja_JP

```
You can create new albums by using the /{user-id}/albums or /{page-id}/albums edges.
```

**Comment by sunojvijayan** [comment]
I noticed that the graph api uses get method. How can we change it to post.

**Comment by aogilvie** [comment]
@sunojvijayan ah, I see you need to do a post, we don't have that available yet.. BUT, you can build an XHR POST using the FB REST api. (you can get the secret for your XHR POST using `facebookConnectPlugin.getAccessToken() `)
If you want to assist (pull request) adding the post solution I've written down the requirements here: 
https://github.com/Wizcorp/phonegap-facebook-plugin/issues/562

**Comment by sunojvijayan** [comment]
Will post be available in the near future?
