### ISSUE TITLE
facebook plugin is not defined 

### ISSUE THREAD

**Issue by promactkaran** [Wizcorp/phonegap-facebook-plugin#930]
I have to check login status when the app is first opened. In my controller.js I have made this 

app.controller('SigninCtrl', function ($scope, $cordovaOauth, $cordovaFacebook , $location) {
     
$cordovaFacebook.getLoginStatus().then(
            function(success) {
               if (success.status == 'connected'){
                  $location.path ('/home')
               }
            }, function (err) {
                console.log(err);
                alert(err);
            });
})

I always get a facebookplugin not defined, but when I call the same function from $scope.login() function, it works.

**Comment by aogilvie** [comment]
You need to wait for 'deviceready' event. See PhoneGap documentation for more information on events and plugins.
