### ISSUE TITLE
Android command line build Hask Key issue

### ISSUE THREAD

**Issue by sunojvijayan** [Wizcorp/phonegap-facebook-plugin#932]
Hi,

I am facing a small issue while using the plugin for Android. I this I could be doing something wrong here. I created a project, added the plugin and all. This works fine in IOS. But in Android i am getting an error "Invalid key hash".

I have created the Android platform via CLI. I have created a Hash key with the following code

keytool -exportcert -alias FbReleaseKey -keystore Keyhash | D:\openssl-0.9.8k_X64\bin\openssl.exe sha1 -binary | D:\openssl-0.9.8k_X64\bin\openssl.exe base64

I ran the Android App via CLI cordova run android.

Am I doing something wrong. Please help?

**Comment by kaansoral** [comment]
Just keep trying until you get it right, previously the plugin reported the expected hash by itself, so you just could test and enter the required hash, however this wasn't the case last time, I checked my logs, but couldn't find the exact command to generate the hash

But this might help you: http://stackoverflow.com/questions/21785283/facebook-key-hash-error-using-facebookconnect-plugin-with-phonegap-build

**Comment by aogilvie** [comment]
@sunojvijayan yes, please generate a valid hash.
