### ISSUE TITLE
login works only first time of adding app to my fb apps...

### ISSUE THREAD

**Issue by emps** [Wizcorp/phonegap-facebook-plugin#934]
than when i try again login i get errors of Key Hashes
invalid key hash.. the key hash... dose not match.. 
and bject {errorMessage: "Facebook error: Session was closed and was not closed normally"}

any one please know why ?
keys are ok cause first time no problem, if i go to my fp apps and remove the app,
and use the plugin for login it works again and second time i press its fails again

"
On the first connection, all work fine but if the user delete the app and install it again, i have an error on the facebook connection : "Invalid key hash. The key hash xxxxxxxxxx does not match any stored key hashes.Configure your app key hashes at
"

**Comment by promactkaran** [comment]
I was facing the same issue. What i did was let my Facebook app decide the hash key for me. 
for example, I login for the first time. it worked fine. when i click on login again it shows invalid hash key. 

Invalid key hash. The key hash xxxxxxxxxx does not match any stored key hashes.Configure your app key hashes at....."

Copy this xxxxxxxx key to your development hask key on your facebook app's setting page . and this should resolve "invalid key hash errors"

and for {errorMessage: "Facebook error: Session was closed and was not closed normally"}. 
make sure you call the $cordovaFacebook.logout() function before trying to login again.

**Comment by emps** [comment]
yeh thanks i took that key too and used some how the key i gen not working

**Comment by raoulcimpean** [comment]
You solved the problem , I have same issues ... and i can`t figureit out

**Comment by onlyfrank** [comment]
I still got the error: Facebook error: Session was closed and was not closed normally.. it appears ONLY if user have already accepted permissions and is trying to login again. any news?

**Comment by onlyfrank** [comment]
K got it working, had the weird windows 64bit hash problem.. make sure to use OpenSSL for Windows (not 0.9.8k)
