### ISSUE TITLE
Getting error 5 from facebook when requesting album list

### ISSUE THREAD

**Issue by marie-dk** [Wizcorp/phonegap-facebook-plugin#946]
Hello everyone... I really don't like to bother you busy people, but I've struggled with this all day, and it's time to throw the towel into the ring.

I am working on an app where user is able to select an image from his/hers facebook album.

It works like a charm with phonegap-facebook-plugin 0.10.1, but in version 0.11.0 I get this message back in calls to graph api: "**The operation couldn’t be completed. (com.facebook.sdk error 5.)**"

My request string is:
me/albums?limit=10&fields=name,id,picture,count,photos.limit(10){images}
... and it works fine in Facebook graph explorer. Also I checked that the user_photos permission is in fact granted.
I found a similar issue #906, but don't think I need to have facebook review my use of user_photos, since my app is still in development mode on facebook. 

```javascript
function api(params,service) {
   var deferred = $.Deferred();
   params || (params = '');
   service || (service = "me");
   if (params) params = "/"+params;
   console.log("Request string: "+service+params);
   facebookConnectPlugin.api(service+params,[],
   function(data) {
     deferred.resolve(data);
   },
   function (errObj) {
     var msg = errHandler("api",errObj);
     deferred.reject(msg);
   });
   return deferred.promise();
}
```
The console says:
"Request string: me/albums?limit=10&fields=name,id,picture,count,photos.limit(10){images}"

... so in short I am doing this:
```javascript
facebookConnectPlugin.api("me/albums?limit=10&fields=name,id,picture,count,photos.limit(10){images}",[], function(data) {}, function (errObj) {});
```
Something must be different with version 0.11.0, but I am embarrassed to admit that I just can't figure it out.

Thank you so much for all the hard work you are doing with this plugin :-)

** Edit 1 ** 
Don't know if this is relevant, but I'll add it just in case:
It worked on Linux with device Android 4.4.2, plugin 0.10.1 and Cordova 3.6
Does not work on Android 4.4.2 nor iOS 8.1 on Mac with Xcode 6.1, plugin 0.11.0 and Cordova 4.2

** Edit 2 **
According to the SDK doc, errors are objects like this... but it seems that the plugin only returns the message?? 
    {
      "error": {
        "message": "Message describing the error", 
        "type": "OAuthException", 
        "code": 190,
        "error_subcode": 460,
        "error_user_title": "A title",
        "error_user_msg": "A message"
      }
    }

** Edit 3 **
Downloaded and installed plugin 0.10.1 but still I get the same error... I am really missing the ability to get the complete error object. Is there a way I can achieve this?

** Edit 4 **
Since I reverted back to plugin version 0.10.1 it works with Android. Installed a proxy to get the full error from facebook. But discovered that no request is even made from iOS when this error occurs. If I shorten the request to something like me/albums?limit=10&fields=name,id,picture,count the request is made, and no error occurs. There is a valid response from facebook, but it never hits the "success" callback.

**Comment by marie-dk** [comment]
Since I have not been able to solve this issue, I have chosen to bypass the plugin and do a plain ajax call directly to the Facebook api for album lists and photos on iOS. It's ugly but it works :-) I hope this bug is fixed in the near future.

**Comment by DanceSC** [comment]
Try this instead
facebookConnectPlugin.api("me/albums?limit=10&fields=name,id,picture,count,photos.limit(10).fields(images)",[], function(data) {}, function (errObj) {});

The difference is replacing the { } with .fields( )

**Comment by marie-dk** [comment]
Thanks @DanceSC I'll try that :-)
