### ISSUE TITLE
getLoginStatus returns unknown after app restart

### ISSUE THREAD

**Issue by avivais** [Wizcorp/phonegap-facebook-plugin#957]
When I first run the app and run login function I get the authResponse as needed and everything works fine.
Then, I restart the app and call getLoginStatus - It immediately returns "unknown".

Is this intended?
Obviously it doesn't make sense to re-login after every restart, perhaps I'm missing something?

**Comment by lyonsrob** [comment]
@avivais I see you closed this issue. How were you able to resolve this?

**Comment by avivais** [comment]
Actually it was my fault - I called logout (by mistake) prior to
getLoginStatus resulting in the unknown state

On Friday, April 17, 2015, lyonsrob <notifications@github.com> wrote:

> @avivais <https://github.com/avivais> I see you closed this issue. How
> were you able to resolve this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wizcorp/phonegap-facebook-plugin/issues/957#issuecomment-94016737>
> .
>


-- 
Avi Vaisenberger
Co-Founder & CTO
Fabula Gaming <http://www.fabulagame.com>
+972-50-766-6550

**Comment by lyonsrob** [comment]
So your able to satisfy this use case?

- launch app
- login with FB / accept connection
- hard close app (double click and swipe)
- open app, user is still logged in and connected to FB?

I'm also not sure if this is just an issue with my access tokens.

**Comment by avivais** [comment]
Yes, the flow you mentioned is working as expected

Avi Vaisenberger
Co-Founder & CTO
Fabula Gaming <http://www.fabulagame.com>
+972-50-766-6550

**Comment by lyonsrob** [comment]
I'll take a look at my setup tonight. Would you mind sharing your scripts
with me? I'd love to see how you set it up.
