### ISSUE TITLE
Error invalid Key Hash...

### ISSUE THREAD

**Issue by over12** [Wizcorp/phonegap-facebook-plugin#961]
I have this error:

"Invalid key hash. The Key Hash <MyHash> does not match any stored key hases. configure you app key hashes at...."

The first time I ran the application does not appear this message appeared my profile and the OK button to confirm the permissions in the application...

But the second time this message appears, if I press an OK button he apparently also connects but that would not be showing this message.

My question is, every time that is compiling the application for testing will need to create a new key?

Thanks!

**Comment by aogilvie** [comment]
No the hash is just required once or in some strange scenarios like you change development devices.
