### ISSUE TITLE
Update Facebook Plugin to use android-support-v13.jar

### ISSUE THREAD

**Issue by vscholz** [Wizcorp/phonegap-facebook-plugin#964]
Hi everyone,

The plugin uses right now android-support-v4.jar and in combination with the pushplugin, which uses android-support-v13.jar, the build breaks.

As far as I understand does the android-support-v13.jar support all functions of android-support-v4.jar. 

**Which files do I need to change to use android-support-v13.jar?**

Thank you!
Valentin

**Comment by ReneMoraales** [comment]
To solve this problem, I just replaced v4 with v13 then renamed it back to v4 in the plugin's folder. It worked like a charm.

**Comment by vscholz** [comment]
Thanks
