### ISSUE TITLE
installed plugin's plugin.xml looks nothing like the one here

### ISSUE THREAD

**Issue by toom1984** [Wizcorp/phonegap-facebook-plugin#967]
the iOS instructions say to git-clone and install from the clone, but that version plugin.xml says its v 0.3.2 yet the plugin.xml shown on the main folder here is v 0.11.0 and looks completely different and uses the facebookConnectPlugin.js while the git clone version does not. The examples shows seem to be relevant to the 0.11.0 version but not the git clone installed version. 

I have had it working on iOS with version 0.7.0 which looks similar to the 0.11.0 version and uses the facebookConnectPlugin.js. However, something went wrong with my iOS build and had to create a new build and add all the plugins again.  Now I am confused as to which version of the code i should use. 

 A clarification of instructions and examples would be nice. Thanks

**Comment by aogilvie** [comment]
Perhaps you are on the wrong git branch? This is the latest on `master`: https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/plugin.xml#L5
