### ISSUE TITLE
Windows Phone Support

### ISSUE THREAD

**Issue by quape** [Wizcorp/phonegap-facebook-plugin#971]
Hi there
is there any change to advance this nice plugin to Windows Phone?
So far I have not figured out how to manage to make a FB connect on WP.

**Comment by vanuatu** [comment]
Same ISSUE here! we need some support to WP8. tks

**Comment by moperacz** [comment]
+1

**Comment by vtellez** [comment]
+1

**Comment by aogilvie** [comment]
No native support scheduled. There is however a JavaScript SDK embedded. You can use that when on WP.

**Comment by vtellez** [comment]
Could you tell us more about how to use this JS SDK on WP? I really need this.

Thanks in advance
