### ISSUE TITLE
Share without login

### ISSUE THREAD

**Issue by butlimous** [Wizcorp/phonegap-facebook-plugin#974]
Hi,

I have an android app. I want to show the share dialog without forcing the user to login to my app. I supposed automatically that the plugin would use the FB session when sharing but when I tried to invoke the dialog via the  "facebookConnectPlugin.showdialog" method, I got "No active session" error.

I have enabled single sign on, deep linking, and the correct key hash. Calling the login dialog works well. Is anyone facing this issue?

Thanks
Regards
Michael

**Comment by Clawg** [comment]
Did you ever solve this issue, I am having the same problem

**Comment by butlimous** [comment]
It seems there is no way to do it without login. Unlike the website where It would work if the user is just logged in to Facebook. I ended up using the social sharing plugin instead

**Comment by glsarmenta** [comment]
Any Update?
