### ISSUE TITLE
Android Build Error: Multiple Dex filed defined (Steps to reproduce)

### ISSUE THREAD

**Issue by deliverymanager** [Wizcorp/phonegap-facebook-plugin#992]
Cordova CLI 5.0.0
Android cordova@4.0.0

Please reproduce the bug to verify it with me:
ionic start freshproject
cd freshproject
ionic hooks add
ionic platform add android
ionic build android (Should give success)
ionic plugin add com.phonegap.plugins.PushPlugin
ionic build android (should give success)
cordova -d plugin add /path/to/facebookplugin/phonegap-facebook-plugin --variable APP_ID="14582388977XXX" --variable APP_NAME="APP name"
cordova build android (should fail and give error)

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)

:dexDebug FAILED

I think that the issue is caused because the PushPlugin and the Facebook Connect plugin are using different versions of gradle. I am not sure though.
But it is a fact that the error happens only if I combine the two modules.
If only one of them exists, then there is not error in the build!

**Comment by deliverymanager** [comment]
Looks like the issue is exactly as the error shows.
The two plugins are using different version of android sdk.
Push Plugin uses v13
Facebook Plugin uses v4
It cannot work with both plugins and with two different sdk.

This error only appeared after upgrading to the Cordova CLI 5.0

So, to solve this I replaced the android-support-v4.jar by android-support-v13.jar which exists inside the FacebookLib file inside the platforms/android/com.phonegap.plugins.facebookconnect 
more details here:
https://github.com/phonegap-build/PushPlugin/issues/492
and here:
http://stackoverflow.com/questions/20989317/multiple-dex-files-define-landroid-support-v4-accessibilityservice-accessibility

**Comment by Ziv-Barber** [comment]
Not working because both plugins need this jar.

**Comment by aogilvie** [comment]
Not sure what happened, but there was work to try create a dependency plugin for android-v4 https://github.com/Wizcorp/phonegap-facebook-plugin/issues/750

**Comment by pupupu93** [comment]
For me it worked by removing the android-v4 plugin via Cordova CLI.
The android-v4 plugin is already included, if you use minTargetSDK above X (not sure about the specific version, I have minTarget 22).

Just do in Cordova CLI: "cordova plugin list" and then "cordova plugin rm [name of androidv4 plugin]

this worked fine for me.

**Comment by kaansoral** [comment]
It's not added for me, the plugin manually adds the v4 library

Why android/cordova version are you using, is it the latest?

**Comment by pupupu93** [comment]
I use Córdoba 4.0 i think. You must delete the v4 library plugin manually after installing the facebook plugin

**Comment by animista01** [comment]
I've the same problem, where is the v4 library plugin? It is not in my project.

**Comment by jannone** [comment]
I'm having the same problem. None of these workarounds work for me.

**Comment by jorisw** [comment]
This worked for me: `cordova plugin remove android.support.v4`

Do a `cordova plugin list` to see which one you need to remove.

**Comment by YoniH** [comment]
Updating dependency in the Facebook plugin to android-support-v13 seems to work for me.

Here is how I did it:

1. Go to <app root>\plugins\com.phonegap.plugins.facebookconnect\platforms\android\FacebookLib\libs

2. Replace android-support-v4.jar with android-support-v13.jar (you can find the v13 file somewhere in the Push plugin dir)

3. (I’m not sure if this step is important) In the same directory, there’s a file called BUCK. Text replace all android-support-v4 in it with android-support-v13 (2 occurences).

4. In <app root>\plugins\com.phonegap.plugins.facebookconnect\platforms\android\FacebookLib (one level above), edit build.gradle and under the dependencies section, text replace support-v4 with support-v13.

5. To remove any caches and intermediate builds, I re-added the android platform to the project. In ionic:
	ionic platform rm android
	ionic platform add android

6. Rebuild

**Comment by shprink** [comment]
This works for me:

```
cp plugins/com.phonegap.plugins.PushPlugin/src/android/com/plugin/android-support-v13.jar plugins/com.phonegap.plugins.facebookconnect/platforms/android/FacebookLib/libs/
rm plugins/com.phonegap.plugins.facebookconnect/platforms/android/FacebookLib/libs/android-support-v4.jar
```

**Comment by duplikey** [comment]
Any news about this bug?
I tried all the solutions in this page and none of it works for me.

I also updated the pushplugin to the version 2.5.0

**Comment by christopher5106** [comment]
have a try to remove the plugin, remove the platform android, re-create the platform android, add the plugin

**Comment by duplikey** [comment]
@christopher5106 you mean without using any workaround on this page?

**Comment by christopher5106** [comment]
No just following the readme
my commands in the Facebook section on http://christopher5106.github.io/mobile/2015/04/09/create-mobile-app-with-html-css-cordova.html

**Comment by duplikey** [comment]
@christopher5106 I tried and it still doesn't work :(

My commands were:
cordova plugin rm com.phonegap.plugins.facebookconnect
cordova platform rm android
cordova platform add android
cordova -d plugin add /path/to/phonegap-facebook-plugin --variable APP_ID="XXX" --variable APP_NAME="YYY"
ionic build android

And I still get the error:
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;

**Comment by christopher5106** [comment]
Ok sorry then, i really don t get the error with this plugin in my case

**Comment by kaansoral** [comment]
Just use the Telerik versions of both plugins, they are actively developed and are free of this issue

**Comment by duplikey** [comment]
@kaansoral
do you mean https://github.com/Telerik-Verified-Plugins/Facebook and https://github.com/Telerik-Verified-Plugins/PushNotification?

**Comment by kaansoral** [comment]
yes exactly, they are forks, the maintainer fixed the issues, he also fixes other issues when they arise, no need to put your hopes and efforts into these original/unmaintained/mis-maintained versions

**Comment by duplikey** [comment]
@kaansoral thanks a lot for the info! I'll try right now.
It seems to me that the facebook plugin still need to be installed cloning the repo locally. Is that right?

**Comment by duplikey** [comment]
@kaansoral I just tried with those two plugins and I still have the same error :(
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;

**Comment by kaansoral** [comment]
As far as I know, you have to start fresh, as far as I remember, removing this plugin and adding the fixed plugins is not enough

I have a routine that re-creates my project and adds plugins from scratch, I left this problem behind long ago, so I can safely say that it works for me

I would suggest you try this, create 2 test projects, add the original 2 plugins to one of them, add the telerik plugins to the other one, and build them :)

**Comment by duplikey** [comment]
@kaansoral I tried again using the steps:

remove plugins
remove platform android
add platform android
install plugins

and... it works! Man, you made my day... thanks a lot! <3

**Comment by kaansoral** [comment]
Np, I'm glad I could help :)

(Ps. Eddy might be on vacation, the push plugin's play services import clashes with the google analytics plugins's - just something to watch out for, I reported the issue, I'm sure he will fix it soon, otherwise, compared to this issue, that issue is easy to fix, a recent change to the analytics plugin triggered the issue by the way)

**Comment by brunosouza** [comment]
hi @kaansoral , i'm having the same issue, but instead of push plugin i'm using admobpro. I've already installed the Telerik Facebook plugin.

**Comment by kaansoral** [comment]
Then your best bet is to try and apply some of the manual solutions proposed with the admobpro plugin

I've never seen/used that plugin myself, so I can't be of any help, sorry

**Comment by dot-louis** [comment]
@kaansoral, @duplikey thanks for your tips on the Telerik fork, it worked.
You helped me preserved my sanity.

**Comment by rahilwazir** [comment]
@kaansoral, @duplikey Thanks so much!

**Comment by amitsinha559** [comment]
@christopher5106 Solution worked for me

Remove the plugin
Remove the platform
Add platform
Add plugin

**Comment by alexklibisz** [comment]
@christopher5106 @kaansoral @duplikey Thank you all very much. Very helpful.

**Comment by JWesorick** [comment]
After trying the fix from @christopher5106 I am still getting this error. I even get the error after completely removing both plugins (PushNotification and Facebook)! Am I missing something?

```shell
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/ads/AdRequest$ErrorCode;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
```

**Comment by kaansoral** [comment]
Sometimes you have to re-create the project, the libraries stick even if you remove/re-add plugins (at least this was the case months ago when I was trying things, pre-eddy/telerik libraries)

Also, the issue is pretty os/library-method specific, that's why some people have solutions that don't work for others

**Comment by rahilwazir** [comment]
I'm also getting the same error `UNEXPECTED TOP-LEVEL EXCEPTION:` when only trying to build release `.apk`

    cordova build --release android

**Comment by alexklibisz** [comment]
For what it's worth, switching to a fork of this plugin fixed the build problems for me: https://github.com/jeduan/cordova-plugin-facebook4

I now have been able to get my build to work with the following plugins (from my package.json file):

```
"cordovaPlugins": [
    "com.ionic.keyboard",
    "cordova-plugin-whitelist",
    "cordova-plugin-inappbrowser",
    "org.apache.cordova.dialogs",
    {
      "locator": "https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin",
      "id": "cordova-plugin-x-toast"
    },
    {
      "locator": "https://github.com/jeduan/cordova-plugin-facebook4",
      "id": "cordova-plugin-facebook4",
      "variables": {
        "APP_ID": "000111222333444",
        "APP_NAME": "MyApp"
      }
    },
    {
      "locator": "https://github.com/phonegap/phonegap-plugin-push",
      "id": "phonegap-plugin-push"
    },
    {
      "locator": "https://github.com/apache/cordova-plugin-device",
      "id": "cordova-plugin-device"
    }
  ]
```

```cordova build android``` and ```cordova build android --release``` both work for this setup.

**Comment by jgraffite** [comment]
I've did the merge of some answers that have posted here. So, I did a tutorial showing how to use that plugins together the crosswalk browser.

See the link, on the Google Docs. In the begin, it is in Portuguese language. But, after it, there is the same text in english.

Check out:

https://docs.google.com/document/d/1kH-Hc0o7CMxK4fgqKD4se-yokwkpwMPlZpEpqnRzmio/edit?usp=sharing

This can help you 'cause is working for me

**Comment by danielsaidi** [comment]
Hi everyone! Just wanted to thank you all for sharing your experiences with this problem, and add a quick note regarding my own huuuuge problems with getting this to work (and finally actually getting it to work).

I struggled like crazy with replacing the v4 support library with a v13 one. I followed all pieces of advice above and dug through crash logs and documentation like a mad man, but could still not get it to work.

Then...after creating a new project, and adding my project's plugins one after another, I found out that it was not the Parse plugin that caused my problems. Or rather, the v13 fix worked to get Facebook and Parse to play together, but the problem I was stuck with (which made me believe that the v13 fix did not work) was instead the Google Analytics plugin. As soon as I added that plugin, I received the dex error.

I then returned to my non-working project, removed the GA plugin, removed the Android platform (if I did not do this, it still would not build) then ran `npm install` to regenerate the Android platform. After that, I could build the android project without any problems whatsoever.

**Comment by aaronfranco** [comment]
I confirm @alexklibisz answer. Switching to the https://github.com/jeduan/cordova-plugin-facebook4 plugin resolves this issue when using the Google Analytics plugin. I have not tried this with the push plugin. However, it appears this version of the Facebook plugin does not include an Android support library, so there is no conflict.

**Comment by raphaelduartepinheiro** [comment]
Solution for me was:

`cordova plugin remove cordova-plugin-googleplayservices`

Since it's not necessary anymore:
https://github.com/EddyVerbruggen/cordova-plugin-googleplus/commit/2ded53244cd4400e0893d58f109d8edc17241503

And add this line to build.gradle: `configurations { all*.exclude group: 'com.android.support', module: 'support-v4' }`

**Comment by ambujsharma23** [comment]
@raphaelduartepinheiro   Thanks a lot buddy. I tried all of above, nothing worked. But this line in build.gradle: **configurations { all*.exclude group: 'com.android.support', module: 'support-v4' }**
has just saved me from doing suicide... Thanks a lot..

**Comment by akz92** [comment]
Thank you @alexklibisz your solutions worked for me. Just used: https://github.com/jeduan/cordova-plugin-facebook4 instead of the original one.
It's now working with the following plugins:

    cl.rmd.cordova.dialoggps 0.0.2 "DialogGPS"
    cordova-plugin-camera 1.2.0 "Camera"
    cordova-plugin-console 1.0.1 "Console"
    cordova-plugin-device 1.0.1 "Device"
    cordova-plugin-facebook4 1.3.0-0 "Facebook Connect"
    cordova-plugin-geolocation 1.0.1 "Geolocation"
    cordova-plugin-splashscreen 2.1.0 "Splashscreen"
    cordova-plugin-statusbar 1.0.1 "StatusBar"
    cordova-plugin-whitelist 1.0.0 "Whitelist"
    ionic-plugin-keyboard 1.0.7 "Keyboard"
    plugin.google.maps 1.3.4 "phonegap-googlemaps-plugin"

**Comment by tomasbedrich** [comment]
Thank you, I can also confirm that @alexklibisz's solution works for me.

**Comment by sliard** [comment]
Just for information, in my case this solution don't work.
In fact, I need this lib for runtime. So build is ok, but my app crash at runtime.

I find a solution if I change the build.gradle of platforms/android/phonegap-facebook-plugin/project-FacebookLib

I change dependencies like that :
```
dependencies {
    compile fileTree(dir: 'libs', include: 'bolts-android-1.1.2.jar')
    compile 'com.android.support:support-v4:23.1.1'
    debugCompile project(path: ":CordovaLib", configuration: "debug")
    releaseCompile project(path: ":CordovaLib", configuration: "release")
}
```
the problem is that this file are rewrite at each cordova build.
So I build my app with gradle : gradle cdvBuildRelease

The question is why Facebook plugin host the android-support-v4.jar and don't use gradle dependencies...

**Comment by kaansoral** [comment]
I know this isn't helping anyone but the Telerik solution no longer works too, currently there is a google-play-services clash that prevents the push plugin from working, the fb plugin works tho (I reported the issue months ago, no reply/solution)

These issues are very moody, the cause is the constant, endless changes to the cordova platform

- change plugin format
- change plugin format
- change build tooling
- move to npm

It seems like every 2-3 months there is a breaking change, and the community and community developers are simply not dynamic enough to keep up, most plugins get updated yearly

Anyway, as an off topic but related advice, the best thing to do is to delay solving the issue until the last moment and at the last moment, dive as deeper as you have to go and manually patch the issue for one stable archive to upload

**Comment by alxferraz** [comment]
http://stackoverflow.com/a/32559386/3654502

**Comment by VinceOPS** [comment]
Thanks @alxferraz 

It did the trick here too :)

EDIT - However, I was also able to solve the issue by using the plugin from Telerik: https://github.com/Telerik-Verified-Plugins/Facebook
(Ionic Project)
I had to remove my platforms/ and plugins/ folders, then run command "ionic state restore". Thus, I followed the installation procedure again using Telerik's Plugin. (1 - git clone their repo, 2 - cordova plugin -d add .... -> See the instructions for Android installation).

**Comment by maurozac** [comment]
Yes, this is the way: http://stackoverflow.com/a/32559386/3654502

**Comment by xyboox** [comment]
@raphaklaus Thank YOU!
"And add this line to build.gradle: configurations { all*.exclude group: 'com.android.support', module: 'support-v4' }" - life saver!

**Comment by maurozac** [comment]
One more tip: you can overwrite the original compiled file /platforms/android/FacebookLib/libs/android-support-v4.jar that cames in the plugin with the last version of the same library that you can find in your updated Android SDK: [android-sdk-macsox]/extras/android/support/v4/android-support-v4.jar

This will give you the last look and fell (currently Android 23)

**Comment by abcd-ca** [comment]
[Telerik version](https://github.com/Telerik-Verified-Plugins/Facebook) that @kaansoral mentioned worked for me and is a drop-in replacement for the Wizcorp, official one. Same API and fixed my Android issue without needing to fiddle with support jars. Thanks @kaansoral !

**Comment by kaansoral** [comment]
Np :)

Eddy also fixes other issues when they arise or reported, that version can also use the old native auth process on iOS 9 for example

**Comment by jackmasi** [comment]
Finally its working follow the way of : http://stackoverflow.com/a/32559386/3654502
