### ISSUE TITLE
Facebook SDK v4.1.0 and corodva plugins migrated to npm

### ISSUE THREAD

**Issue by talamaska** [Wizcorp/phonegap-facebook-plugin#994]
Are you planning an update of the plugin.
A lot of Cordova apps are relying on your plugin, it's the only one and it wasn't updated for quite a while. I received an update that Cordova plugins are migrated to npm and this is a requirement for other 3rd party plugins too.

**Comment by jrouault** [comment]
This plugin is now on npm. See #1060.
