### ISSUE TITLE
FB IOS API Update

### ISSUE THREAD

**Issue by milad-xdg** [Wizcorp/phonegap-facebook-plugin#998]
please , FB on 28th of April 2015 announced  that they will update all the IOS API on 30th of April 2015

i have an incoming deadline and all the FB functionalities are stopped now

please please , update the plugin ASAP

I'm screwed

**Comment by deliverymanager** [comment]
What isn't working exactly after the update?

**Comment by milad-xdg** [comment]
FB login & share in All IOS devices

**Comment by deliverymanager** [comment]
It is working fine on my iOS device. I don't think it is related to the FB update.
What error do you get when trying to login?
About SDK deprecation?

**Comment by deliverymanager** [comment]
It might have something to do with the plugin but not with the update of FB.
The error appears in a production app or in development?
The problem only appears if you try to login?
Did you try rebuilding the app?
Do you test on a real device?

**Comment by milad-xdg** [comment]
- the error appears in development app , it was working fine for the last month till yesterday

- the problem appears if i try to login using FB , yes

- i tried rebuilding the app several times , the android build is working fine and the ios isn't
and i tried also the remove and reinstall the plugin using git and the problem didn't fixed

- yes i test on real devices which was working befor ( ipad and iphone )

PS : i'm working on 2 platforms android and ios
the problem appears only in the ios , that's why i thought it was the API
the android version is working perfectly as before

**Comment by deliverymanager** [comment]
Do you use any special permissions in your FB app, or just the default (email, public_profile, friends_list)?
This error appears in the console.log or in FB login window?

**Comment by milad-xdg** [comment]
i use only email, public_profile
and this error appears in the console

FB login window doesn't open at all , when i click on the button of the login nothing happen , just this error in the console of the xcode

**Comment by deliverymanager** [comment]
This is weird.
The only thing I could suggest is to start a blank project with just the login button, then place the same plugins in the app and then test on the device. 
And of course, re clone the git of the FB plugin and then re add it.
Something is wrong, in the app or something got stuck.
Because I am too just testing and building the app and it seems to be working fine on iOS.
Of course make sure you have all the settings in your FB app correctly set on facebook developer site.

**Comment by milad-xdg** [comment]
okay , thanks for your time

i'll try it out

**Comment by aogilvie** [comment]
Possible developer error. Do update us if you have more information.
