### ISSUE TITLE
Facebook SDK v4 support

### ISSUE THREAD

**Issue by serhanbuy** [Wizcorp/phonegap-facebook-plugin#999]
Hi there,
I am using this plugin but since facebook updated its sdk to v4 recently, we can't apply some new rules of facebook like app invites.

Are there any plans to upgrade the framework SDK version bundled in the plugin?

thanks

**Comment by adeelraza** [comment]
+1

**Comment by christopher5106** [comment]
+1

**Comment by rodrigoplant** [comment]
+1

**Comment by thiagomorato** [comment]
+1

**Comment by jdwiartanto** [comment]
+1

**Comment by MingxuanLi** [comment]
+1

**Comment by aogilvie** [comment]
Yes, there are plans, it:s currently in progress. A lot has changed, no eta as yet.
